# MenuTitle: Make Glyphs
# Author: Ben Jones
__doc__ = """
Adds ingredients/components to the currently selected glyph(s).
"""

import math
from collections import defaultdict
the_font = Glyphs.font

force_build = 0
Glyphs.clearLog()
# Glyphs.showMacroWindow()


class recipesLister:
    class recipeList:
        class component:
            def __init__(self, comp_args):
                comp_recipe = comp_args.split(' ')
                self.name = comp_recipe.pop(0)
                self.in_font = the_font.glyphs[self.name]
                for arg in comp_recipe:
                    setattr(self, arg, True)

            def __str__(self):
                return self.name

            def __getattr__(self, attrname):
                return False

        def __init__(self, all_recipes, glyph_name, **kwargs):
            self.all_recipes = all_recipes
            self.glyph_name = glyph_name
            self.italic = kwargs.get('italic', False)

        def __iter__(self):
            return iter(self._getRecipeList())

        def __str__(self):
            return ''.format(self._getRecipeList())

        def _getRecipeList(self):
            if self.italic:
                return self.all_recipes.get(self.glyph_name + 'italic', self.all_recipes.get(self.glyph_name, []))
            else:
                return self.all_recipes.get(self.glyph_name, [])

        def addRecipe(self, *args, **kwargs):
            if self.all_recipes.get(self.glyph_name) is None:
                comp_objs = [self.component(x) for x in args]
                if all([x.in_font for x in comp_objs]):
                    if kwargs.get('italic', False):
                        self.all_recipes[self.glyph_name + 'italic'] = comp_objs
                    else:
                        self.all_recipes[self.glyph_name] = comp_objs

    def __init__(self):
        self.all_recipes = defaultdict(list)
        self.accent_tops = self._get_accent_tops()
        self.accent_bottoms = self._get_accent_bottoms()

    def __call__(self, glyph_name, **kwargs):
        return self.recipeList(self.all_recipes, glyph_name, **kwargs)

    def has_recipe(self, glyph_name, **kwargs):
        if self.recipeList(self.all_recipes, glyph_name, **kwargs)._getRecipeList():
            return True
        else:
            return False

    def layer_is_empty(self, layer):
        return not any([layer.bounds.origin.x, layer.bounds.origin.y, layer.bounds.size.height, layer.bounds.size.width])

    def italic_angle(self, layer):
        try:
            return Glyphs.font.masters[layer.associatedMasterId].italicAngle
        except AttributeError:
            return 0

    def compensate_italic_angle(self, pos_y, italic_angle):
        if not italic_angle:
            return 0
        return round(math.tan(math.radians(italic_angle)) * pos_y)

    def _get_accent_tops(self):
        g = Glyphs.font.glyphs['00A8']
        if g is None:
            for gn in ['dieresis', 'dieresiscomb', '00A8']:
                g = Glyphs.font.glyphs[gn]
                if g is not None:
                    break
        if g is None:
            return None
        coord_dict = dict((layer.associatedMasterId, NSPoint(0, Glyphs.font.masters[layer.associatedMasterId].ascender)) for layer in g.layers)
        if g is not None:
            for layer in g.layers:
                if not self.layer_is_empty(layer):
                    coord_dict[layer.associatedMasterId] = layer.bounds.origin
        return coord_dict

    def _get_accent_bottoms(self):
        g = Glyphs.font.glyphs['0326']
        if g is None:
            for gn in ['commaaccent', 'commaaccentcomb', 'uni0326']:
                g = Glyphs.font.glyphs[gn]
                if g is not None:
                    break

        if g is None:
            return

        coord_dict = dict((layer.associatedMasterId, NSPoint(0, int(-69000.0 / Glyphs.font.upm))) for layer in g.layers)
        if g is not None:
            for layer in g.layers:
                if not self.layer_is_empty(layer):
                    coord_dict[layer.associatedMasterId] = NSPoint(0, layer.bounds.origin.y + layer.bounds.size.height)
        return coord_dict

    def transform_position_y(self, from_coords, to_coords, italic_angle=0):
        newy = to_coords.y - from_coords.y
        new_coords = NSPoint(self.compensate_italic_angle(newy, italic_angle), newy)
        return new_coords

    def addComponents(self, this_l):
        this_g = this_l.parent
        glyph_components = this_g.glyphInfo.components
        if glyph_components:
            component_glyphs = [Glyphs.font.glyphs[info.name] for info in glyph_components]
            if None not in component_glyphs:
                for cg in component_glyphs:
                    this_l.components.append(GSComponent(cg))


recipes = recipesLister()

# Latin
recipes('I').addRecipe('_part.stem')
recipes('H').addRecipe('_part.stem', '_part.bar', '_part.stem')
recipes('E').addRecipe('_part.stem', '_part.bar', '_part.bar', '_part.bar')
recipes('F').addRecipe('E decompose')
recipes('L').addRecipe('E decompose')
recipes('T').addRecipe('_part.stem', '_part.bar')
recipes('AE').addRecipe('A decompose', 'E decompose')
recipes('ae').addRecipe('a decompose', 'e decompose')
recipes('Aringacute').addRecipe('A', 'ringcomb', 'acutecomb')
recipes('ae.sc').addRecipe('a.sc decompose', 'e.sc decompose')
recipes('Ldot').addRecipe('L', 'periodcentered.loclCAT')
recipes('Ldot').addRecipe('L', 'dotaccent')
recipes('ldot').addRecipe('l', 'periodcentered.loclCAT')
recipes('ldot').addRecipe('l', 'dotaccent')
recipes('idotless').addRecipe('i decompose')
recipes('jdotless').addRecipe('j decompose')
recipes('Germandbls').addRecipe('I decompose', 'S decompose')
recipes('germandbls').addRecipe('f decompose', 's decompose')
recipes('Tcedilla').addRecipe('T', 'cedillacomb')
recipes('Eth').addRecipe('D', '_part.bar')
recipes('Eth').addRecipe('D', 'macroncomb decompose')
recipes('Hbar').addRecipe('H', '_part.bar')
recipes('Tbar').addRecipe('T', '_part.bar')
recipes('Hbar').addRecipe('H', 'macroncomb decompose')
recipes('Eng').addRecipe('jdotless decompose', 'N decompose')
recipes('eng.sc').addRecipe('jdotless decompose', 'n.sc decompose')
recipes('Dcroat').addRecipe('Eth')
recipes('dcroat.sc').addRecipe('eth.sc')
recipes('dcroat').addRecipe('d', '_part.bar')
recipes('dcroat').addRecipe('d', 'macroncomb decompose')
recipes('iogonek').addRecipe('i', 'ogonekcomb')
recipes('hbar').addRecipe('h', '_part.bar')
recipes('hbar').addRecipe('h', 'macroncomb decompose')
recipes('tbar').addRecipe('t', '_part.bar')
recipes('tbar').addRecipe('t', 'macroncomb decompose')
recipes('kgreenlandic').addRecipe('k decompose')
recipes('eng').addRecipe('jdotless decompose', 'n decompose')
recipes('tcedilla').addRecipe('t', 'cedillacomb')
recipes('tcedilla.sc').addRecipe('t.sc', 'cedillacomb')
recipes('Thorn').addRecipe('P decompose', 'I decompose')
recipes('thorn').addRecipe('p decompose', 'l decompose')
recipes('Lslash').addRecipe('macroncomb decompose', 'L')
recipes('lslash').addRecipe('macroncomb decompose', 'l')
recipes('longs').addRecipe('f decompose')
recipes('Oslash').addRecipe('O', 'slash decompose')
recipes('oslash').addRecipe('o', 'slash decompose')
recipes('OE').addRecipe('O decompose', 'E')
recipes('oe').addRecipe('o', 'e')
recipes('oe.sc').addRecipe('o.sc decompose', 'e.sc')
recipes('napostrophe').addRecipe('quoteright', 'n')
recipes("Ohornacute").addRecipe('Ohorn', 'acutecomb.case')
recipes("Ohornacute").addRecipe('Ohorn', 'acutecomb')
recipes("Ohorndotbelow").addRecipe('Ohorn', 'dotbelowcomb.case')
recipes("Ohorndotbelow").addRecipe('Ohorn', 'dotbelowcomb')
recipes("Ohorngrave").addRecipe('Ohorn', 'gravecomb.case')
recipes("Ohorngrave").addRecipe('Ohorn', 'gravecomb')
recipes("Ohornhookabove").addRecipe('Ohorn', 'hookabovecomb.case')
recipes("Ohornhookabove").addRecipe('Ohorn', 'hookabovecomb')
recipes("Ohorntilde").addRecipe('Ohorn', 'tildecomb.case')
recipes("Ohorntilde").addRecipe('Ohorn', 'tildecomb')
recipes("Uhornacute").addRecipe('Uhorn', 'acutecomb.case')
recipes("Uhornacute").addRecipe('Uhorn', 'acutecomb')
recipes("Uhorndotbelow").addRecipe('Uhorn', 'dotbelowcomb.case')
recipes("Uhorndotbelow").addRecipe('Uhorn', 'dotbelowcomb')
recipes("Uhorngrave").addRecipe('Uhorn', 'gravecomb.case')
recipes("Uhorngrave").addRecipe('Uhorn', 'gravecomb')
recipes("Uhornhookabove").addRecipe('Uhorn', 'hookabovecomb.case')
recipes("Uhornhookabove").addRecipe('Uhorn', 'hookabovecomb')
recipes("Uhorntilde").addRecipe('Uhorn', 'tildecomb.case')
recipes("Uhorntilde").addRecipe('Uhorn', 'tildecomb')
recipes("ohornacute").addRecipe('ohorn', 'acutecomb')
recipes("ohorndotbelow").addRecipe('ohorn', 'dotbelowcomb')
recipes("ohorngrave").addRecipe('ohorn', 'gravecomb')
recipes("ohornhookabove").addRecipe('ohorn', 'hookabovecomb')
recipes("ohorntilde").addRecipe('ohorn', 'tildecomb')
recipes("uhornacute").addRecipe('uhorn', 'acutecomb')
recipes("uhorndotbelow").addRecipe('uhorn', 'dotbelowcomb')
recipes("uhorngrave").addRecipe('uhorn', 'gravecomb')
recipes("uhornhookabove").addRecipe('uhorn', 'hookabovecomb')
recipes("uhorntilde").addRecipe('uhorn', 'tildecomb')
recipes("Acircumflexacute").addRecipe('A', 'circumflexcomb_acutecomb')
recipes("Acircumflexgrave").addRecipe('A', 'circumflexcomb_gravecomb')
recipes("Ecircumflexacute").addRecipe('E', 'circumflexcomb_acutecomb')
recipes("Ecircumflexgrave").addRecipe('E', 'circumflexcomb_gravecomb')
recipes("Ocircumflexacute").addRecipe('O', 'circumflexcomb_acutecomb')
recipes("Ocircumflexgrave").addRecipe('O', 'circumflexcomb_gravecomb')
recipes("acircumflexacute").addRecipe('a', 'circumflexcomb_acutecomb')
recipes("acircumflexgrave").addRecipe('a', 'circumflexcomb_gravecomb')
recipes("ecircumflexacute").addRecipe('e', 'circumflexcomb_acutecomb')
recipes("ecircumflexgrave").addRecipe('e', 'circumflexcomb_gravecomb')
recipes("ocircumflexacute").addRecipe('o', 'circumflexcomb_acutecomb')
recipes("ocircumflexgrave").addRecipe('o', 'circumflexcomb_gravecomb')
recipes("Abrevegrave").addRecipe('A', 'brevecomb_gravecomb')
recipes("Abreveacute").addRecipe('A', 'brevecomb_acutecomb')
recipes('Abrevehookabove').addRecipe('A', 'brevecomb_hookabovecomb')
recipes('Abrevetilde').addRecipe('A', 'brevecomb_tildecomb')
recipes('Acircumflexhookabove').addRecipe('A', 'circumflexcomb_hookabovecomb')
recipes('Acircumflextilde').addRecipe('A', 'circumflexcomb_tildecomb')
recipes('Ecircumflexhookabove').addRecipe('E', 'circumflexcomb_hookabovecomb')
recipes('Ecircumflextilde').addRecipe('E', 'circumflexcomb_tildecomb')
recipes('Ocircumflexhookabove').addRecipe('O', 'circumflexcomb_hookabovecomb')
recipes('Ocircumflextilde').addRecipe('O', 'circumflexcomb_tildecomb')
recipes('abreveacute').addRecipe('a', 'brevecomb_acutecomb')
recipes('abrevegrave').addRecipe('a', 'brevecomb_gravecomb')
recipes('abrevehookabove').addRecipe('a', 'brevecomb_hookabovecomb')
recipes('abrevetilde').addRecipe('a', 'brevecomb_tildecomb')
recipes('acircumflexhookabove').addRecipe('a', 'circumflexcomb_hookabovecomb')
recipes('acircumflextilde').addRecipe('a', 'circumflexcomb_tildecomb')
recipes('ecircumflexhookabove').addRecipe('e', 'circumflexcomb_hookabovecomb')
recipes('ecircumflextilde').addRecipe('e', 'circumflexcomb_tildecomb')
recipes('ocircumflexhookabove').addRecipe('o', 'circumflexcomb_hookabovecomb')
recipes('ocircumflextilde').addRecipe('o', 'circumflexcomb_tildecomb')
recipes('f_i').addRecipe('fi')
recipes('f_l').addRecipe('fl')
recipes('fi').addRecipe('f_i')
recipes('fl').addRecipe('f_l')
recipes('f_f').addRecipe('f', 'f')
recipes('f_f_i').addRecipe('f', 'f', 'i')
recipes('f_f_l').addRecipe('f', 'f', 'l')
recipes('s_t').addRecipe('s', 't')
recipes('schwa').addRecipe('e flip_vertical flip_horizontal')
recipes('Schwa').addRecipe('Schwa-cy')
recipes('Schwa').addRecipe('O decompose', 'two decompose', 'H decompose', italic=True)
recipes('Schwa').addRecipe('G decompose flip_horizontal')
recipes('Schwa').addRecipe('schwa decompose')
recipes('nmod').addRecipe('n.sups')
recipes('nmod').addRecipe('n.sups')
recipes('n.subs').addRecipe('nmod')
recipes('Abrevedotbelow').addRecipe('A', 'brevecomb', 'dotbelowcomb')
recipes('Acircumflexdotbelow').addRecipe('A', 'circumflexcomb', 'dotbelowcomb')
recipes('Ecircumflexdotbelow').addRecipe('E', 'circumflexcomb', 'dotbelowcomb')
recipes('Ocircumflexdotbelow').addRecipe('O', 'circumflexcomb', 'dotbelowcomb')
recipes('abrevedotbelow').addRecipe('a', 'brevecomb', 'dotbelowcomb')
recipes('acircumflexdotbelow').addRecipe('a', 'circumflexcomb', 'dotbelowcomb')
recipes('ecircumflexdotbelow').addRecipe('e', 'circumflexcomb', 'dotbelowcomb')
recipes('ocircumflexdotbelow').addRecipe('o', 'circumflexcomb', 'dotbelowcomb')
recipes('germandbls.sc').addRecipe('s.sc', 's.sc')
recipes('gcommaaccent').addRecipe('g', 'commaturnedabovecomb')


recipes("alpha-latin").addRecipe('alpha')
recipes("alphaturned-latin").addRecipe('alpha')
recipes("Aturned").addRecipe('A flip_horizontal flip_vertical')
recipes("aturned").addRecipe('a flip_vertical')
recipes("bilabialclick").addRecipe('O', 'dotaccentcomb')
recipes("Bsmall").addRecipe('ve-cy')
recipes("clickdental").addRecipe('bar decompose')
recipes("clickalveolar").addRecipe('clickdental', '_part.bar', '_part.bar')
recipes("clicklateral").addRecipe('clickdental', 'clickdental')
recipes("clickretroflex").addRecipe('exclam')
recipes("Thook").addRecipe('T decompose', '_part.Hookleft decompose')
recipes("Bhook").addRecipe('B', '_part.Hookleft')
recipes("Phook").addRecipe('P', '_part.Hookleft')
recipes("Hhook").addRecipe('H', '_part.Hookleft')
recipes("Chook").addRecipe('C', '_part.Hook')
recipes("chook").addRecipe('c', '_part.hook')
recipes("Dafrican").addRecipe('Eth')
recipes("dezh").addRecipe('d', 'ezh')
recipes("Dhook").addRecipe('D', '_part.Hookleft')
recipes("dhook").addRecipe('d decompose', '_part.hook')
recipes("dtail").addRecipe('d', '_part.hook')
recipes("dhookandtail").addRecipe('dhook', '_part.hook')
recipes("eopen").addRecipe('ze-cy decompose')
recipes("eopenreversed").addRecipe('ze-cy')
recipes("eopenreversed").addRecipe('ze-cy')
recipes("eopenreversedclosed").addRecipe('ze-cy decompose')
recipes("eopenreversedhook").addRecipe('eopenreversed', '_part.hook')
recipes("ereversed").addRecipe('e decompose')
recipes("esh").addRecipe('f decompose')
recipes("gamma-latin").addRecipe('v decompose')
recipes("Ghook").addRecipe('G', '_part.hook')
recipes("ghook").addRecipe('gsingle', '_part.hook')
recipes("glottalstop").addRecipe('question decompose')
recipes("glottalstopreversed").addRecipe('glottalstop flip_horizontal')
recipes("glottalstopstroke").addRecipe('glottalstop', '_part.bar')
recipes("glottalstopstrokereversed").addRecipe('glottalstopreversed', '_part.bar')
recipes("gsingle").addRecipe('q decompose', 'y decompose')
recipes("henghook").addRecipe('hhook', '_part.hook')
recipes("hhook").addRecipe('n', '_part.hook')
recipes("Hsmall").addRecipe('en-cy')
recipes("hturned").addRecipe('h flip_horizontal flip_vertical')
recipes("Istroke").addRecipe('I', '_part.bar')
recipes("istroke").addRecipe('i', '_part.bar')
recipes("jcrossedtail").addRecipe('j decompose')
recipes("jdotlessstroke").addRecipe('jdotless', '_part.bar')
recipes("jdotlessstrokehook").addRecipe('jdotlessstroke', '_part.hook')
recipes("khook").addRecipe('kgreenlandic', '_part.hook')
recipes("Kturned").addRecipe('K flip_horizontal flip_vertical')
recipes("kturned").addRecipe('k flip_horizontal flip_vertical')
recipes("lbelt").addRecipe('l', 'zcurl decompose')
recipes("lezh").addRecipe('l', 'ezh')
recipes("lhookretroflex").addRecipe('l', '_part.hook')
recipes("Lmiddletilde").addRecipe('L', '_part.tilde')
recipes("lmiddletilde").addRecipe('l', '_part.tilde')
recipes("Mhook").addRecipe('M', '_part.hook flip_horizontal flip_vertical')
recipes("mhook").addRecipe('m', '_part.hook flip_horizontal flip_vertical')
recipes("mlonglegturned").addRecipe('m flip_horizontal flip_vertical', '_part.stem flip_horizontal flip_vertical')
recipes("mturned").addRecipe('m flip_horizontal flip_vertical')
recipes("Nhookleft").addRecipe('N', '_part.hook flip_horizontal flip_vertical')
recipes("nhookleft").addRecipe('n', '_part.hook flip_horizontal flip_vertical')
recipes("nhookretroflex").addRecipe('n', '_part.hook flip_vertical')
recipes("obarred").addRecipe('obarred-cy')
recipes("Ocenteredtilde").addRecipe('Obarred-cy')
recipes("Oopen").addRecipe('C flip_horizontal flip_vertical')
recipes("oopen").addRecipe('c flip_horizontal flip_vertical')
recipes("phi-latin").addRecipe('phi')
recipes("ramshorn").addRecipe('gamma-latin decompose')
recipes("rfishhook").addRecipe('_part.stem', '_part.hook')
recipes("rhook").addRecipe('r', '_part.hook flip_vertical')
recipes("rhookturned").addRecipe('rturned', '_part.hook flip_vertical')
recipes("rlonglegturned").addRecipe('rturned', '_part.stem flip_horizontal flip_vertical')
recipes("Rsmallinverted").addRecipe('Rsmall')
recipes("Tretroflexhook").addRecipe('T', '_part.Hook flip_vertical')
recipes("Rtail").addRecipe('R', '_part.Hook flip_vertical')
recipes("rturned").addRecipe('r flip_horizontal flip_vertical')
recipes("schwahook").addRecipe('schwa decompose', 'eopenreversedhook decompose')
recipes("shook").addRecipe('s', '_part.hook flip_vertical')
recipes("vrighthook").addRecipe('v decompose', '_part.hook decompose')
recipes("tesh").addRecipe('t', 'esh')
recipes("tretroflexhook").addRecipe('t decompose')
recipes("ubar").addRecipe('u', '_part.bar')
recipes("vhook").addRecipe('u decompose', '_part.hook flip_horizontal')
recipes("vturned").addRecipe('v flip_horizontal flip_vertical')
recipes("vturned").addRecipe('v')
recipes("wturned").addRecipe('w flip_horizontal flip_vertical')
recipes("yturned").addRecipe('y flip_horizontal flip_vertical')
recipes("zcurl").addRecipe('z decompose', 'ccurl decompose')
recipes("zretroflexhook").addRecipe('z', '_part.hook flip_vertical')
recipes("Upsilonafrican").addRecipe('Omega flip_vertical flip_horizontal')
recipes("Tturned").addRecipe('T flip_vertical flip_horizontal')
recipes("Kturned").addRecipe('K flip_vertical flip_horizontal')
recipes("Glottalstop").addRecipe('glottalstop decompose')
recipes("glottalstopsmall").addRecipe('glottalstop decompose')
recipes("Iotaafrican").addRecipe('iota decompose')
recipes("Vturned").addRecipe('V flip_vertical flip_horizontal')
recipes("Nlongrightleg").addRecipe('Shha-cy decompose')
recipes("Esh").addRecipe('Sigma')
recipes("Ubar").addRecipe('U', '_part.bar')
recipes("Alpha-latin").addRecipe('D flip_vertical flip_horizontal decompose', 'I decompose')
recipes("Alphaturned-latin").addRecipe('Alpha-latin flip_vertical flip_horizontal')
recipes("Ezh").addRecipe('ezh decompose')
recipes("Eopen").addRecipe('Ze-cy flip_horizontal decompose')
recipes("EreversedOpen").addRecipe('Ze-cy')
recipes("Qhooktail").addRecipe('Alpha-latin', '_part.Hook flip_vertical')
recipes("Mturned").addRecipe('u decompose', 'I decompose')
recipes("Gammaafrican").addRecipe('gamma-latin decompose')
recipes("Jcrossedtail").addRecipe('J decompose', 'jcrossedtail decompose')
recipes("Khook").addRecipe('K decompose', '_part.Hook decompose')
recipes("Lbelt").addRecipe('L', 'lbelt decompose')
recipes("Gscript").addRecipe('Alpha-latin decompose', 'gsingle decompose')
recipes("Whook").addRecipe('W decompose', 'Khook decompose')
recipes("Vhook").addRecipe('vhook decompose', 'U decompose')
recipes("mpalatalhook").addRecipe('m', '_part.hook flip_vertical flip_horizontal')
recipes("minusmod").addRecipe('macron')
recipes("plusmod").addRecipe('plusbelowcomb')
recipes("dzaltone").addRecipe('d', 'z')
recipes("dzcurl").addRecipe('d', 'zcurl')
recipes("ts").addRecipe('t', 's')
recipes("tccurl").addRecipe('t decompose', 'ccurl decompose')
recipes("dblarchinvertedbelowcomb").addRecipe('seagullbelowcomb flip_vertical flip_horizontal')
recipes("macronacutecomb").addRecipe('macron decompose', 'acute decompose')
recipes('gravemacroncomb').addRecipe('macronacutecomb flip_horizontal')
recipes('macrongravecomb').addRecipe('macroncomb decompose', 'gravecomb decompose')
recipes('acutemacroncomb').addRecipe('macrongravecomb flip_horizontal')
recipes('graveacutegravecomb').addRecipe('caron decompose', 'circumflex decompose')
recipes('acutegraveacutecomb').addRecipe('graveacutegravecomb flip_horizontal')
recipes('closeup').addRecipe('undertie', 'breveinverteddoublecomb')
recipes('Usmall').addRecipe('u decompose')
recipes('hv').addRecipe('h decompose', 'vhook decompose')
recipes('lambdastroke').addRecipe('lambda', 'eth decompose')
recipes('lbar').addRecipe('l', '_part.bar')

recipes("bridgebelowcomb").addRecipe('minusbelowcomb decompose')
recipes("bridgeinvertedbelowcomb").addRecipe('bridgebelowcomb flip_vertical')
recipes("colontriangularhalfmod").addRecipe('periodcentered decompose')
recipes("colontriangularmod").addRecipe('colontriangularhalfmod', 'colontriangularhalfmod flip_vertical')
recipes("dblverticalbar").addRecipe('bar', 'bar')
recipes("downtackbelowcomb").addRecipe('uptackbelowcomb flip_vertical flip_horizontal')
recipes("downtackmod").addRecipe('uptackmod flip_vertical')
recipes("leftangleabovecomb").addRecipe('lefttackbelowcomb decompose')
recipes("lefttackbelowcomb").addRecipe('uptackmod decompose')
recipes("minusbelowcomb").addRecipe('lefttackbelowcomb', 'lefttackbelowcomb flip_horizontal')
recipes("plusbelowcomb").addRecipe('lefttackbelowcomb decompose', 'lefttackbelowcomb flip_vertical')
recipes("rhotichookmod").addRecipe('eopenreversedhook decompose')
recipes("righttackbelowcomb").addRecipe('lefttackbelowcomb flip_horizontal')
recipes("ringhalfleftbelowcomb").addRecipe('ringhalfrightbelowcomb flip_horizontal')
recipes("ringhalfrightbelowcomb").addRecipe('brevecomb')
recipes("seagullbelowcomb").addRecipe('brevecomb decompose', 'brevecomb decompose')
recipes("squarebelowcomb").addRecipe('bridgebelowcomb', 'bridgebelowcomb flip_vertical')
recipes("tildeoverlaycomb").addRecipe('asciitilde decompose', 'z')
recipes("tonebarextrahighmod").addRecipe('plus decompose')
recipes("tonebarextralowmod").addRecipe('tonebarextrahighmod flip_vertical')
recipes("tonebarhighmod").addRecipe('tonebarextrahighmod decompose')
recipes("tonebarlowmod").addRecipe('tonebarhighmod flip_vertical')
recipes("tonebarmidmod").addRecipe('tonebarextrahighmod decompose')
recipes("undertie").addRecipe('parenleft')
recipes("uptackbelowcomb").addRecipe('lefttackbelowcomb decompose')
recipes("uptackmod").addRecipe('plus decompose')
recipes("verticallinebelowcomb").addRecipe('macroncomb decompose')
recipes("verticallinelowmod").addRecipe('verticallinemod')
recipes("verticallinemod").addRecipe('verticallinebelowcomb')


# Cyrillic

recipes('Be-cy').addRecipe('Softsign-cy', 'F decompose')
recipes('Che-cy').addRecipe('u decompose', 'I decompose')
recipes('Cheabkhasian-cy').addRecipe('ie-cy decompose', '_part.hook')
recipes('Chedescender-cy').addRecipe('Che-cy', 'toothright-cy')
recipes('Chedescenderabkhasian-cy').addRecipe('Cheabkhasian-cy', '_part.toothcentered-cy')
recipes('Chedescenderabkhasian-cy').addRecipe('Cheabkhasian-cy', 'toothcentered-cy')
recipes('Chekhakassian-cy').addRecipe('Che-cy', 'toothleft-cy')
recipes('De-cy').addRecipe('El-cy decompose', 'Tse-cy decompose')
recipes('De-cy.loclBGR').addRecipe('De-cy decompose', 'Lambda')
recipes('Dje-cy').addRecipe('T decompose', 'b decompose')
recipes('Dzeabkhasian-cy').addRecipe('Ezh')
recipes('Dzeabkhasian-cy').addRecipe('seven decompose', 'five decompose')
recipes('Dzhe-cy').addRecipe('Tsebase-cy', '_part.toothcentered-cy')
recipes('Dzhe-cy').addRecipe('Tsebase-cy', 'toothcentered-cy')
recipes('E-cy').addRecipe('C', 'E decompose')
recipes('E-cy').addRecipe('C', '_part.bar')
recipes('Ef-cy').addRecipe('Phi')
recipes('Ef-cy.loclBGR').addRecipe('O', 'I decompose')
recipes('El-cy').addRecipe('el-cy decompose')
recipes('El-cy.loclBGR').addRecipe('Lambda')
recipes('Elhook-cy').addRecipe('El-cy decompose', 'J decompose')
recipes('Elhook-cy').addRecipe('El-cy', '_part.Hook flip_horizontal flip_vertical')
recipes('Eltail-cy').addRecipe('El-cy', 'tail-cy')
recipes('Emtail-cy').addRecipe('Em-cy', 'tail-cy')
recipes('Enghe-cy').addRecipe('En-cy', 'Te-cy decompose')
recipes('Enhook-cy').addRecipe('En-cy', '_part.Hook flip_horizontal flip_vertical')
recipes('Entail-cy').addRecipe('En-cy', 'tail-cy')
recipes('Ereversed-cy').addRecipe('C decompose', 'E decompose')
recipes('Esdescender-cy').addRecipe('Es-cy', 'Zedescender-cy decompose')
recipes('Fita-cy').addRecipe('O-cy', '_part.centertilde')
recipes('Ge-cy').addRecipe('F decompose')
recipes('Ge-cy').addRecipe('Gamma')
recipes('Gedescender-cy').addRecipe('Ge-cy', 'toothright-cy')
recipes('Ghemiddlehook-cy').addRecipe('Ge-cy', 'Dje-cy decompose')
recipes('Ghestroke-cy').addRecipe('Ge-cy', '_part.bar')
recipes('Ghestroke-cy').addRecipe('Ge-cy', 'macroncomb decompose')
recipes('Haabkhasian-cy').addRecipe('O decompose')
recipes('Hahook-cy').addRecipe('X decompose', '_part.hook flip_horizontal flip_vertical')
recipes('Hardsign-cy').addRecipe('Softsign-cy', 'T decompose')
recipes('Ia-cy').addRecipe('Softsign-cy decompose', 'Zhe-cy decompose')
recipes('Iu-cy').addRecipe('I-cy', 'O-cy', 'macroncomb decompose')
recipes('Izhitsa-cy').addRecipe('V decompose', 'izhitsa-cy decompose')
recipes('Kabashkir-cy').addRecipe('Ka-cy', 'Te-cy decompose')
recipes('Kahook-cy').addRecipe('Ka-cy decompose', 'Ghemiddlehook-cy decompose')
recipes('Kastroke-cy').addRecipe('Ka-cy', '_part.bar')
recipes('Kadescender-cy').addRecipe('Ka-cy', 'toothright-cy')
recipes('Lje-cy').addRecipe('El-cy decompose', 'Softsign-cy')
recipes('Nje-cy').addRecipe('H decompose', 'Softsign-cy decompose')
recipes('Obarred-cy').addRecipe('O-cy', '_part.bar')
recipes('Pedescender-cy').addRecipe('Pe-cy', 'toothright-cy')
recipes('Pemiddlehook-cy').addRecipe('Pe-cy', 'Ghemiddlehook-cy decompose')
recipes('Reversedze-cy').addRecipe('Eopen')
recipes('Reversedze-cy').addRecipe('Ze-cy')
recipes('Schwa-cy').addRecipe('Schwa')
recipes('Shha-cy').addRecipe('Che-cy decompose')
recipes('Shcha-cy').addRecipe('Sha-cy', 'toothright-cy')
recipes('Shhadescender-cy').addRecipe('Shha-cy', 'toothright-cy')
recipes('Softsign-cy').addRecipe('B decompose')
recipes('Tedescender-cy').addRecipe('Te-cy', 'toothright-cy')
recipes('Tetse-cy').addRecipe('Tse-cy', 'Te-cy decompose')
recipes('Tetse-cy').addRecipe('Tse-cy', '_part.bar')
recipes('Tshe-cy').addRecipe('Shha-cy', 'T decompose')
recipes('U-cy').addRecipe('y decompose')
recipes('Ustraight-cy').addRecipe('Y')
recipes('Ustraightstroke-cy').addRecipe('Ustraight-cy', '_part.bar')
recipes('We-cy').addRecipe('W')
recipes('Yat-cy').addRecipe('Softsign-cy', 'T decompose')
recipes('Yeru-cy').addRecipe('Softsign-cy', 'I-cy')
recipes('Yi-cy.loclUKR').addRecipe('I', 'dieresiscomb decompose')
recipes('Ze-cy').addRecipe('three decompose')
recipes('Zhedescender-cy').addRecipe('Zhe-cy', 'toothright-cy')
recipes('Zedescender-cy').addRecipe('Ze-cy', 'ogonekcomb flip_horizontal decompose')
recipes('Zedescender-cy').addRecipe('Ze-cy', 'zedescender-cy decompose')
recipes('Zhe-cy').addRecipe('Ka-cy', 'Ka-cy decompose')
recipes('be-cy.loclMKD').addRecipe('be-cy.loclSRB')
recipes('be-cy.loclSRB').addRecipe('delta decompose', 'be-cy decompose')
recipes('cheabkhasian-cy').addRecipe('ie-cy', '_part.hook rotate_90')
recipes('chedescender-cy').addRecipe('che-cy', 'toothright-cy')
recipes('chedescenderabkhasian-cy').addRecipe('cheabkhasian-cy', '_part.toothcentered-cy')
recipes('chedescenderabkhasian-cy').addRecipe('cheabkhasian-cy', 'toothcentered-cy')
recipes('chekhakassian-cy').addRecipe('che-cy', 'toothleft-cy')
recipes('de-cy.loclBGR').addRecipe('de-cy.loclSRB', italic=True)
recipes('de-cy.loclBGR').addRecipe('g')
recipes('de-cy.loclBGR').addRecipe('q decompose', 'jdotless decompose')
recipes('de-cy.loclMKD').addRecipe('de-cy.loclSRB')
recipes('de-cy.loclSRB').addRecipe('g')
recipes('dje-cy').addRecipe('hbar decompose', 'jdotless decompose')
recipes('dzeabkhasian-cy').addRecipe('ezh')
recipes('dzeabkhasian-cy').addRecipe('ze-cy decompose', 'seven decompose')
recipes('el-cy.loclBGR').addRecipe('v flip_horizontal flip_vertical')
recipes('elhook-cy').addRecipe('el-cy decompose', 'jdotless decompose')
recipes('es-cy').addRecipe('c')
recipes('elhook-cy').addRecipe('el-cy', '_part.hook flip_horizontal flip_vertical')
recipes('eltail-cy').addRecipe('el-cy', 'tail-cy')
recipes('emtail-cy').addRecipe('em-cy', 'tail-cy')
recipes('endescender-cy').addRecipe('en-cy', 'toothright-cy')
recipes('enghe-cy').addRecipe('en-cy', 'te-cy decompose')
recipes('enhook-cy').addRecipe('en-cy', '_part.hook flip_horizontal flip_vertical')
recipes('entail-cy').addRecipe('en-cy', 'tail-cy')
recipes('esdescender-cy').addRecipe('es-cy', 'zedescender-cy decompose')
recipes('fita-cy').addRecipe('o-cy', '_part.centertilde')
recipes('ge-cy.loclBGR').addRecipe('ge-cy', italic=True)
recipes('ge-cy.loclBGR').addRecipe('s decompose', 'c', 'schwa-cy')
recipes('ge-cy.loclBGR').addRecipe('s decompose', 'c')
recipes('ge-cy.loclMKD').addRecipe('ge-cy.loclSRB')
recipes('ge-cy.loclMKD').addRecipe('imacron')
recipes('ge-cy.loclSRB').addRecipe('imacron')
recipes('gedescender-cy').addRecipe('ge-cy', 'toothright-cy')
recipes('ghemiddlehook-cy').addRecipe('ge-cy', 'dje-cy decompose')
recipes('ghestroke-cy').addRecipe('ge-cy', '_part.bar')
recipes('ghestroke-cy').addRecipe('ge-cy', 'macroncomb decompose')
recipes('Hastroke-cy').addRecipe('Ha-cy', '_part.bar')
recipes('ha-cy').addRecipe('x')
recipes('hastroke-cy').addRecipe('ha-cy', '_part.bar')
recipes('haabkhasian-cy').addRecipe('o decompose')
recipes('hahook-cy').addRecipe('x decompose', '_part.hook flip_vertical flip_horizontal')
recipes('hardsign-cy.loclBGR').addRecipe('softsign-cy.loclBGR', 'hardsign-cy decompose')
recipes('ii-cy').addRecipe('u', italic=True)
recipes('ii-cy.loclBGR').addRecipe('u')
recipes('iu-cy').addRecipe('idotless', 'o-cy', '_part.bar')
recipes('iu-cy').addRecipe('idotless', 'o-cy', 'macroncomb decompose')
recipes('iu-cy.loclBGR').addRecipe('iu-cy decompose', 'l decompose')
recipes('izhitsa-cy').addRecipe('v decompose', '_part.hook decompose')
recipes('izhitsa-cy').addRecipe('vrighthook')
recipes('ka-cy.loclBGR').addRecipe('ka-cy decompose', 'l decompose')
recipes('kabashkir-cy').addRecipe('ka-cy', 'te-cy decompose')
recipes('kadescender-cy').addRecipe('ka-cy', 'toothright-cy')
recipes('kahook-cy').addRecipe('ka-cy decompose', 'ghemiddlehook-cy decompose')
recipes('kastroke-cy').addRecipe('ka-cy', '_part.bar')
recipes('lje-cy').addRecipe('el-cy decompose', 'softsign-cy')
recipes('nje-cy').addRecipe('en-cy decompose', 'softsign-cy')
recipes('pe-cy').addRecipe('n', italic=True)
recipes('pe-cy.loclBGR').addRecipe('n')
recipes('pe-cy.loclMKD').addRecipe('pe-cy.loclSRB')
recipes('pe-cy.loclMKD').addRecipe('umacron')
recipes('pe-cy.loclSRB').addRecipe('umacron')
recipes('pedescender-cy').addRecipe('pe-cy', 'toothright-cy')
recipes('pemiddlehook-cy').addRecipe('pe-cy', 'ghemiddlehook-cy decompose')
recipes('reversedze-cy').addRecipe('ze-cy')
recipes('schwa-cy').addRecipe('schwa')
recipes('sha-cy.loclBGR').addRecipe('u decompose')
recipes('shcha-cy.loclBGR').addRecipe('sha-cy.loclBGR', 'toothright-cy')
recipes('shhadescender-cy').addRecipe('shha-cy', 'toothright-cy')
recipes('softsign-cy.loclBGR').addRecipe('softsign-cy decompose')
recipes('te-cy').addRecipe('m', italic=True)
recipes('te-cy.loclBGR').addRecipe('m')
recipes('te-cy.loclMKD').addRecipe('sha-cy', 'macroncomb')
recipes('te-cy.loclMKD').addRecipe('te-cy.loclSRB')
recipes('te-cy.loclSRB').addRecipe('sha-cy', 'macron')
recipes('tedescender-cy').addRecipe('te-cy', 'toothright-cy')
recipes('tetse-cy').addRecipe('tse-cy', 'macroncomb')
recipes('tetse-cy').addRecipe('tse-cy', 'te-cy decompose')
recipes('tse-cy.loclBGR').addRecipe('ii-cy.loclBGR', 'toothright-cy')
recipes('tshe-cy').addRecipe('hbar')
recipes('ustraight-cy').addRecipe('v decompose', 'idotless decompose')
recipes('ustraitstroke-cy').addRecipe('ustraight-cy', '_part.bar')
recipes('ve-cy.loclBGR').addRecipe('beta decompose')
recipes('we-cy').addRecipe('w')
recipes('yat-cy').addRecipe('pe-cy', 'softsign-cy decompose', italic=True)
recipes('yat-cy').addRecipe('softsign-cy', 'T decompose')
recipes('yat-cy').addRecipe('softsign-cy', '_part.stem', '_part.bar')
recipes('yi-cy.loclUKR').addRecipe('idotless', 'dieresiscomb decompose')
recipes('ze-cy.loclBGR').addRecipe('schwa-cy decompose', 'dzeabkhasian-cy decompose')
recipes('zedescender-cy').addRecipe('ze-cy', 'ogonekcomb flip_horizontal decompose')
recipes('zhe-cy.loclBGR').addRecipe('zhe-cy decompose', 'ka-cy.loclBGR decompose')
recipes('uk-cy').addRecipe('o-cy', 'u-cy')
recipes('Koppa-cy').addRecipe('Es-cy', '_part.stem')
recipes('koppa-cy').addRecipe('es-cy', '_part.stem')
recipes('Gestrokehook-cy').addRecipe('Ghestroke-cy', 'tail-cy')
recipes('gestrokehook-cy').addRecipe('ghestroke-cy', 'tail-cy')
recipes('Semisoftsign-cy').addRecipe('Softsign-cy', '_part.bar')
recipes('semisoftsign-cy').addRecipe('softsign-cy', '_part.stem', '_part.bar')
recipes('semisoftsign-cy').addRecipe('softsign-cy', '_part.bar')

recipes('be-cy.sc').addRecipe('softsign-cy.sc', 'f.sc decompose')
recipes('che-cy.sc').addRecipe('u.sc decompose', 'i.sc decompose')
recipes('de-cy.sc').addRecipe('el-cy.sc decompose', 'tse-cy.sc decompose')
recipes('dje-cy.sc').addRecipe('t.sc decompose', 'b.sc decompose')
recipes('dzhe-cy.sc').addRecipe('tsebase-cy.sc', '_part.toothcentered-cy')
recipes('dzhe-cy.sc').addRecipe('tsebase-cy.sc', 'toothcentered-cy')
recipes('e-cy.sc').addRecipe('c.sc', 'e.sc decompose')
recipes('ef-cy.sc').addRecipe('phi.sc')
recipes('el-cy.sc').addRecipe('el-cy.sc decompose')
recipes('enhook-cy.sc').addRecipe('h.sc decompose', 'j.sc decompose')
recipes('ereversed-cy.sc').addRecipe('c.sc decompose', 'e.sc decompose')
recipes('ertick-cy.sc').addRecipe('er-cy.sc', 'macron decompose')
recipes('esdescender-cy.sc').addRecipe('c.sc decompose', 'ogonekcomb decompose')
recipes('ghestroke-cy.sc').addRecipe('ge-cy.sc', '_part.bar')
recipes('ghestroke-cy.sc').addRecipe('ge-cy.sc', 'macroncomb decompose')
recipes('hardsign-cy.sc').addRecipe('softsign-cy.sc', 't.sc decompose')
recipes('ia-cy.sc').addRecipe('softsign-cy.sc decompose', 'zhe-cy.sc decompose')
recipes('iu-cy.sc').addRecipe('i-cy.sc', 'o-cy.sc', 'macroncomb decompose')
recipes('ii-cy.sc').addRecipe('h.sc decompose')
recipes('kabashkir-cy.sc').addRecipe('ka-cy.sc decompose', 'hardsign-cy.sc decompose')
recipes('lje-cy.sc').addRecipe('el-cy.sc decompose', 'softsign-cy.sc')
recipes('nje-cy.sc').addRecipe('h.sc decompose', 'softsign-cy.sc decompose')
recipes('obarred-cy.sc').addRecipe('o-cy.sc', 'obarred-cy decompose')
recipes('pemiddlehook-cy.sc').addRecipe('pi.sc', 'ghemiddlehook-cy.sc decompose')
recipes('semisoftsign-cy.sc').addRecipe('softsign-cy.sc decompose', 'hbar decompose')
recipes('sha-cy.sc').addRecipe('h.sc decompose')
recipes('shha-cy.sc').addRecipe('che-cy.sc decompose')
recipes('softsign-cy.sc').addRecipe('b.sc decompose')
recipes('tshe-cy.sc').addRecipe('shha-cy.sc', 't.sc decompose')
recipes('tsebase-cy.sc').addRecipe('h.sc decompose')
recipes('u-cy.sc').addRecipe('y.sc decompose')
recipes('ustraitstroke-cy.sc').addRecipe('y.sc', 'macroncomb decompose')
recipes('yat-cy.sc').addRecipe('softsign-cy.sc', 't.sc decompose')
recipes('ze-cy.sc').addRecipe('three decompose')
recipes('zhe-cy.sc').addRecipe('ka-cy.sc', 'ka-cy.sc decompose')
recipes('zhedescender-cy.sc').addRecipe('zhe-cy.sc', 'obarred-cy decompose')
recipes('zedescender-cy.sc').addRecipe('ze-cy.sc decompose', 'ogonekcomb decompose')
recipes('kahook-cy.sc').addRecipe('ka-cy.sc decompose', 'ghemiddlehook-cy.sc decompose')
recipes('de-cy.sc.loclBGR').addRecipe('de-cy.sc decompose', 'lambda.sc')
recipes('ef-cy.sc.loclBGR').addRecipe('o.sc decompose', 'i.sc decompose')
recipes('el-cy.sc.loclBGR').addRecipe('lambda.sc')
recipes('Uk-cy').addRecipe('O-cy', 'u-cy')
recipes('Omega-cy').addRecipe('U decompose', 'V decompose')
recipes('Eiotified-cy').addRecipe('Iu-cy decompose', 'E-cy')
recipes('Yuslittle-cy').addRecipe('A decompose', 'I decompose')
recipes('Yuslittleiotified-cy').addRecipe('Iu-cy decompose', 'Yuslittle-cy')
recipes('Yusbig-cy').addRecipe('A decompose', 'manat decompose')
recipes('Yusbigiotified-cy').addRecipe('Iu-cy decompose', 'Yusbig-cy')
recipes('omega-cy').addRecipe('Omega-cy decompose')
recipes('Psi-cy').addRecipe('Psi')
recipes('psi-cy').addRecipe('u decompose', 'l decompose')
recipes('eiotified-cy').addRecipe('iu-cy decompose', 'e-cy')
recipes('yuslittle-cy').addRecipe('t decompose', 'i decompose', 'v decompose')
recipes('yuslittleiotified-cy').addRecipe('iu-cy decompose', 'yuslittle-cy')
recipes('yusbig-cy').addRecipe('v decompose', 'manat decompose', '_part.bar')
recipes('yusbigiotified-cy').addRecipe('iu-cy decompose', 'yusbig-cy')
recipes('Ertick-cy').addRecipe('Er-cy', '_part.bar')
recipes('ertick-cy').addRecipe('er-cy', '_part.bar')
recipes('uni047A').addRecipe('O-cy', '_part.stem')
recipes('uni047B').addRecipe('o-cy', '_part.stem')
recipes('uni047E').addRecipe('Omega-cy', 'tabovecomb-cy')
recipes('uni047E').addRecipe('Omega-cy', 't.sc decompose')
recipes('uni047E').addRecipe('Omega-cy', 'T decompose')
recipes('uni047F').addRecipe('omega-cy', 'tabovecomb-cy')
recipes('uni047F').addRecipe('omega-cy', 't.sc decompose')
recipes('uni047F').addRecipe('omega-cy', 'T decompose')
recipes('uni047C').addRecipe('Omega-cy.base', 'psilipneumatacomb-cy', 'pokrytiecomb-cy')
recipes('uni047D').addRecipe('omega', 'psilipneumatacomb-cy', 'pokrytiecomb-cy')
recipes('uni047C').addRecipe('omega decompose', 'commaaccentcomb', 'brevecomb decompose')
recipes('uni047D').addRecipe('omega', 'commaaccentcomb', 'tildecomb decompose')
recipes('Ksi-cy').addRecipe('Ze-cy decompose', 'ogonekcomb decompose', 'ksiaccent')
recipes('Ksi-cy').addRecipe('Ze-cy decompose', 'ogonekcomb decompose', 'caroncomb decompose')
recipes('ksi-cy').addRecipe('ze-cy decompose', 'ogonekcomb decompose', 'ksiaccent')
recipes('ksi-cy').addRecipe('ze-cy decompose', 'ogonekcomb decompose', 'caroncomb decompose')
recipes('pokrytiecomb-cy').addRecipe('tildecomb decompose')
recipes('psilipneumatacomb-cy').addRecipe('commaabovecomb')
recipes('psilipneumatacomb-cy').addRecipe('commaaccentcomb')


# Greek
recipes('Gamma').addRecipe('F decompose')
recipes('Chi').addRecipe('X')
recipes('Delta').addRecipe('increment')
recipes('Delta').addRecipe('A decompose')
recipes('Lambda').addRecipe('A decompose')
recipes('Omega').addRecipe('Ohm')
recipes('Pi').addRecipe('H decompose')
recipes('Xi').addRecipe('E decompose')
recipes('Sigma').addRecipe('Z decompose')
recipes('Upsilon').addRecipe('Y decompose')
recipes('Psi').addRecipe('U decompose', 'I decompose')
recipes('psi').addRecipe('upsilon decompose', 'idotless decompose')
recipes('phi').addRecipe('omicron decompose', 'l decompose')
recipes('Phi').addRecipe('O decompose', 'I decompose')
recipes('dasia').addRecipe('psili flip_horizontal')
recipes('etapsilivaria').addRecipe('eta', 'psilivaria')
recipes('etapsilioxiaypogegrammeni').addRecipe('eta', 'psilioxia', 'ypogegrammenicomb')

recipes('lowernumeral-greek').addRecipe('numeral-greek flip_horizontal flip_vertical')


# Other
recipes('zero.lf').addRecipe('zero', ignore_width=True)
recipes('one.lf').addRecipe('one', ignore_width=True)
recipes('two.lf').addRecipe('two', ignore_width=True)
recipes('three.lf').addRecipe('three', ignore_width=True)
recipes('four.lf').addRecipe('four', ignore_width=True)
recipes('five.lf').addRecipe('five', ignore_width=True)
recipes('six.lf').addRecipe('six', ignore_width=True)
recipes('seven.lf').addRecipe('seven', ignore_width=True)
recipes('eight.lf').addRecipe('eight', ignore_width=True)
recipes('nine.lf').addRecipe('nine', ignore_width=True)

recipes('zero.osf').addRecipe('zero decompose')
recipes('one.osf').addRecipe('one decompose disable_alignment')
recipes('two.osf').addRecipe('two decompose')
recipes('three.osf').addRecipe('three')
recipes('four.osf').addRecipe('four')
recipes('five.osf').addRecipe('five')
recipes('six.osf').addRecipe('six')
recipes('seven.osf').addRecipe('seven')
recipes('eight.osf').addRecipe('eight')
recipes('nine.osf').addRecipe('nine')

recipes('zero.dnom').addRecipe('zero.numr')
recipes('one.dnom').addRecipe('one.numr')
recipes('two.dnom').addRecipe('two.numr')
recipes('three.dnom').addRecipe('three.numr')
recipes('four.dnom').addRecipe('four.numr')
recipes('five.dnom').addRecipe('five.numr')
recipes('six.dnom').addRecipe('six.numr')
recipes('seven.dnom').addRecipe('seven.numr')
recipes('eight.dnom').addRecipe('eight.numr')
recipes('nine.dnom').addRecipe('nine.numr')
recipes('zero.dnom').addRecipe('zero.subs')
recipes('one.dnom').addRecipe('one.subs')
recipes('two.dnom').addRecipe('two.subs')
recipes('three.dnom').addRecipe('three.subs')
recipes('four.dnom').addRecipe('four.subs')
recipes('five.dnom').addRecipe('five.subs')
recipes('six.dnom').addRecipe('six.subs')
recipes('seven.dnom').addRecipe('seven.subs')
recipes('eight.dnom').addRecipe('eight.subs')
recipes('nine.dnom').addRecipe('nine.subs')
recipes('zero.numr').addRecipe('zero.dnom')
recipes('one.numr').addRecipe('one.dnom')
recipes('two.numr').addRecipe('two.dnom')
recipes('three.numr').addRecipe('three.dnom')
recipes('four.numr').addRecipe('four.dnom')
recipes('five.numr').addRecipe('five.dnom')
recipes('six.numr').addRecipe('six.dnom')
recipes('seven.numr').addRecipe('seven.dnom')
recipes('eight.numr').addRecipe('eight.dnom')
recipes('nine.numr').addRecipe('nine.dnom')
recipes('zero.numr').addRecipe('zero.sups')
recipes('one.numr').addRecipe('one.sups')
recipes('two.numr').addRecipe('two.sups')
recipes('three.numr').addRecipe('three.sups')
recipes('four.numr').addRecipe('four.sups')
recipes('five.numr').addRecipe('five.sups')
recipes('six.numr').addRecipe('six.sups')
recipes('seven.numr').addRecipe('seven.sups')
recipes('eight.numr').addRecipe('eight.sups')
recipes('nine.numr').addRecipe('nine.sups')
recipes('zero.sups').addRecipe('zero.subs')
recipes('one.sups').addRecipe('one.subs')
recipes('two.sups').addRecipe('two.subs')
recipes('three.sups').addRecipe('three.subs')
recipes('four.sups').addRecipe('four.subs')
recipes('five.sups').addRecipe('five.subs')
recipes('six.sups').addRecipe('six.subs')
recipes('seven.sups').addRecipe('seven.subs')
recipes('eight.sups').addRecipe('eight.subs')
recipes('nine.sups').addRecipe('nine.subs')
recipes('zero.subs').addRecipe('zero.sups')
recipes('one.subs').addRecipe('one.sups')
recipes('two.subs').addRecipe('two.sups')
recipes('three.subs').addRecipe('three.sups')
recipes('four.subs').addRecipe('four.sups')
recipes('five.subs').addRecipe('five.sups')
recipes('six.subs').addRecipe('six.sups')
recipes('seven.subs').addRecipe('seven.sups')
recipes('eight.subs').addRecipe('eight.sups')
recipes('nine.subs').addRecipe('nine.sups')
recipes('guillemetleft').addRecipe('guilsinglleft', 'guilsinglleft')
recipes('guillemetright').addRecipe('guillemetleft flip_horizontal')
recipes('guilsinglright').addRecipe('guilsinglleft flip_horizontal')
recipes('dollar').addRecipe('S', '_part.stem')
recipes('dollar').addRecipe('S', 'bar')
recipes('cent').addRecipe('c', '_part.stem')
recipes('cent').addRecipe('c', 'bar')
recipes('franc').addRecipe('F', '_part.bar')
recipes('franc').addRecipe('F', 'minus')
recipes('florin').addRecipe('_part.bar disable_alignment', 'integral')
recipes('florin').addRecipe('integral', 'f decompose')
recipes('ruble').addRecipe('_part.bar disable_alignment', 'P decompose')
recipes('ruble').addRecipe('macroncomb decompose', 'P decompose')
recipes('yen').addRecipe('Y decompose', 'equal decompose')
recipes('euro').addRecipe('C decompose', 'equal decompose')
recipes('liraTurkish').addRecipe('Ech-arm decompose', 'I decompose', 'euro decompose')
recipes('liraTurkish').addRecipe('L decompose', 'euro decompose')
recipes('liraTurkish').addRecipe('L decompose', 'equal decompose')
recipes('lira').addRecipe('sterling decompose')
recipes('peseta').addRecipe('P', 't', 's')
recipes('manat').addRecipe('I decompose', 'Germandbls decompose')
recipes('manat').addRecipe('I', 'sterling decompose')
recipes('rupeeIndian').addRecipe('R decompose', 'sterling decompose')
recipes('dong').addRecipe('dcroat', '_part.bar')
recipes('dong').addRecipe('dcroat', 'underscore')
recipes('kip').addRecipe('K', '_part.bar')
recipes('kip').addRecipe('C', '_part.stem')
recipes('cedi').addRecipe('C', 'dollar decompose')
recipes('cedi').addRecipe('C', '_part.stem')
recipes('colonsign').addRecipe('C', 'slash', 'slash')
recipes('guarani').addRecipe('G', 'dollar decompose')
recipes('guarani').addRecipe('G', '_part.stem')
recipes('guarani').addRecipe('G', 'bar')
recipes('hryvnia').addRecipe('S flip_horizontal decompose', 'lira decompose')
recipes('naira').addRecipe('N', 'lira decompose')
recipes('peso').addRecipe('P', 'lira decompose')
recipes('tenge').addRecipe('T decompose', '_part.bar')
recipes('won').addRecipe('W', '_part.bar')
recipes('tugrik').addRecipe('T', 'liraTurkish decompose')
recipes('bitcoin').addRecipe('B', 'dollar decompose')
recipes('tenge').addRecipe('equal decompose', 'T decompose')
recipes('baht').addRecipe('B', 'dollar decompose')
recipes('baht').addRecipe('B', '_part.stem')
recipes('baht').addRecipe('B', 'bar')
recipes('apple').addRecipe('.notdef')

recipes('cedi').addRecipe('C', 'bar')
recipes('currency').addRecipe('o decompose', 'multiply decompose')
recipes('micro').addRecipe('u decompose', '_part.stem')
recipes('mu').addRecipe('micro')
recipes('percent').addRecipe('zero.numr', 'fraction', 'zero.dnom')
recipes('perthousand').addRecipe('zero.numr', 'fraction', 'zero.dnom', 'zero.dnom')
recipes('onehalf').addRecipe('one.numerator', 'fraction', 'two.denominator')
recipes('onequarter').addRecipe('one.numerator', 'fraction', 'four.denominator')
recipes('threequarters').addRecipe('three.numerator', 'fraction', 'four.denominator')
recipes('integral').addRecipe('f decompose')
recipes('approxequal').addRecipe('asciitilde', 'asciitilde')
recipes('minute').addRecipe('quotesingle')
recipes('second').addRecipe('minute', 'minute')
recipes('pi').addRecipe('n', 't decompose', 't decompose')
recipes('increment').addRecipe('A decompose')
recipes('Ohm').addRecipe('O', 'two decompose')
recipes('lessequal').addRecipe('less', 'minus')
recipes('summation').addRecipe('Z decompose')
recipes('greaterequal').addRecipe('greater', 'minus')
recipes('lozenge').addRecipe('asciicircum decompose', 'asciicircum decompose')
recipes('product').addRecipe('H decompose')
recipes('partialdiff').addRecipe('eth decompose')
recipes('radical').addRecipe('v decompose', 'slash decompose', 'macroncomb decompose')
recipes('exclam').addRecipe('period', '_part.stem')
recipes('interrobang').addRecipe('exclam decompose', 'question decompose')
recipes('at').addRecipe('a', 'copyright decompose')
recipes('divisionslash').addRecipe('slash')
recipes('firsttonechinese').addRecipe('macron')


recipes('periodcentered').addRecipe('period')
recipes('periodcentered.loclCAT').addRecipe('periodcentered')
recipes('exclamdown').addRecipe('exclam flip_vertical')
recipes('quotedbl').addRecipe('quotesingle', 'quotesingle')
recipes('underscore').addRecipe('endash')
recipes('backslash').addRecipe('slash flip_horizontal')
recipes('backslash.sc').addRecipe('slash.sc flip_horizontal')
recipes('braceright').addRecipe('braceleft flip_horizontal')
recipes('braceright.sc').addRecipe('braceleft.sc flip_horizontal flip_vertical')
recipes('bracketright').addRecipe('bracketleft flip_horizontal flip_vertical')
recipes('bracketright.sc').addRecipe('bracketleft.sc flip_horizontal flip_vertical')
recipes('quoteleft').addRecipe('quoteright flip_horizontal flip_vertical')
recipes('quotedblright').addRecipe('quoteright', 'quoteright')
recipes('quotedblleft').addRecipe('quotedblright flip_horizontal flip_vertical')
recipes('quotedblbase').addRecipe('quotedblright')
recipes('quotesinglbase').addRecipe('quoteright')
recipes('quotereversed').addRecipe('quoteright flip_horizontal')
recipes('quotedblrightreversed').addRecipe('quotedblright flip_horizontal decompose', italic=True)
recipes('quotedblrightreversed').addRecipe('quotedblright flip_horizontal')
recipes('question').addRecipe('period', 'two decompose')
recipes('questiondown').addRecipe('question flip_vertical flip_horizontal')
recipes('plusminus').addRecipe('plus', 'minus')
recipes('logicalnot').addRecipe('plus decompose')
recipes('asciitilde').addRecipe('tilde decompose')
recipes('asciitilde').addRecipe('tilde decompose')
recipes('parenright').addRecipe('parenleft flip_horizontal flip_vertical')
recipes('parenright.sc').addRecipe('parenleft.sc flip_horizontal flip_vertical')
recipes('parenright.tf').addRecipe('parenleft.tf flip_horizontal')
recipes('parenright.numr').addRecipe('parenleft.numr flip_horizontal')
recipes('parenright.dnom').addRecipe('parenleft.dnom flip_horizontal')
recipes('parenleft.sups').addRecipe('parenleft.subs')
recipes('parenright.sups').addRecipe('parenleft.sups flip_horizontal flip_vertical')
recipes('parenright-ar').addRecipe('parenleft-ar flip_horizontal')
recipes('greater').addRecipe('less flip_horizontal')
recipes('plus.subs').addRecipe('plus.sups')
recipes('minus.subs').addRecipe('minus.sups')
recipes('equal.subs').addRecipe('equal.sups')
recipes('parenleft.subs').addRecipe('parenleft.sups')
recipes('parenright.subs').addRecipe('parenleft.subs flip_horizontal flip_vertical')
recipes('parenright.subs').addRecipe('parenright.sups')
recipes('nonbreakinghyphen').addRecipe('hyphen')
recipes('hyphentwo').addRecipe('hyphen')
recipes('published').addRecipe('copyright decompose', 'p.sc decompose')
recipes('overline').addRecipe('underscore')
recipes('underscoredbl').addRecipe('underscore', 'underscore')
recipes('apostrophemod').addRecipe('quoteright')
recipes('quotereversed').addRecipe('quoteright flip_horizontal')
recipes('colon').addRecipe('period', 'period')
recipes('semicolon').addRecipe('period', 'comma')
recipes('upArrow').addRecipe('rightArrow rotate_270')
recipes('downArrow').addRecipe('upArrow flip_vertical')
recipes('leftArrow').addRecipe('rightArrow flip_horizontal')
recipes('southEastArrow').addRecipe('northEastArrow flip_vertical')
recipes('northWestArrow').addRecipe('northEastArrow flip_horizontal')
recipes('southWestArrow').addRecipe('northEastArrow flip_horizontal flip_vertical')
recipes('leftRightArrow').addRecipe('rightArrow disable_alignment', 'leftArrow disable_alignment')
recipes('upDownArrow').addRecipe('upArrow disable_alignment', 'downArrow disable_alignment')


recipes('gravecomb').addRecipe('acutecomb flip_horizontal')
recipes('dieresiscomb').addRecipe('dieresis')
recipes('dotaccentcomb').addRecipe('dotaccent')
recipes('hungarumlautcomb').addRecipe('hungarumlaut')
recipes('caroncomb').addRecipe('caron')
recipes('caron').addRecipe('circumflex flip_vertical')
recipes('ringcomb').addRecipe('ring')
recipes('macroncomb').addRecipe('macron')
recipes('commaturnedabovecomb').addRecipe('commaaccentcomb flip_horizontal flip_vertical accent_top')
recipes('commaturnedabovecomb').addRecipe('commaaccent flip_horizontal flip_vertical accent_top')
recipes('commaabovecomb').addRecipe('commaaccent accent_top')
recipes('commaabovecomb').addRecipe('commaaccentcomb accent_top')
recipes('acutecomb').addRecipe('acute')
recipes('circumflexcomb').addRecipe('circumflex')
recipes('brevecomb').addRecipe('breve')
recipes('tildecomb').addRecipe('tilde')
recipes('hookabovecomb').addRecipe('question decompose')
recipes('horncomb').addRecipe('u decompose')
recipes('dotbelowcomb').addRecipe('dotaccent accent_bottom')
recipes('dotbelowcomb').addRecipe('dotaccentcomb accent_bottom')
recipes('dieresisbelowcomb').addRecipe('dieresis accent_bottom')
recipes('dieresisbelowcomb').addRecipe('dieresiscomb accent_bottom')
recipes('ringbelowcomb').addRecipe('ring accent_bottom')
recipes('ringbelowcomb').addRecipe('ringcomb accent_bottom')
recipes('brevebelowcomb').addRecipe('breve accent_bottom')
recipes('brevebelowcomb').addRecipe('brevecomb accent_bottom')
recipes('macronbelowcomb').addRecipe('macron accent_bottom')
recipes('macronbelowcomb').addRecipe('macroncomb accent_bottom')
recipes('ogonekcomb').addRecipe('ogonek')
recipes('cedillacomb').addRecipe('cedilla')
recipes('hamzabelow-ar').addRecipe('hamzaabove-ar')
recipes("breveinvertedbelowcomb").addRecipe('brevecomb flip_vertical')
recipes("breveinverteddoublecomb").addRecipe('undertie flip_vertical')
recipes("caronbelowcomb").addRecipe('caron accent_bottom')
recipes("caronbelowcomb").addRecipe('caroncomb accent_bottom')
recipes("dblgravecomb").addRecipe('hungarumlautcomb flip_horizontal')
recipes("doublegravecomb").addRecipe('hungarumlautcomb flip_horizontal')
recipes("doublegravecomb.case").addRecipe('doublegravecomb')
recipes("tildebelowcomb").addRecipe('tilde accent_bottom')
recipes("doublebrevebelowcomb").addRecipe('undertie')
recipes("halfringrightcomb").addRecipe('ringcomb decompose')
recipes("halfringrightcomb").addRecipe('ring decompose')
recipes("halfringleftcomb").addRecipe('ringcomb decompose')
recipes("halfringleftcomb").addRecipe('ring decompose')
recipes("candrabindu").addRecipe('brevecomb decompose', 'dotaccentcomb')
recipes("halfringrightcomb.case").addRecipe('halfringrightcomb')
recipes("halfringleftcomb.case").addRecipe('halfringleftcomb')

recipes('dialytikaoxia').addRecipe('dieresiscomb', 'oxia')
recipes('dialytikavaria').addRecipe('dieresiscomb', 'varia')
recipes('dasiavaria').addRecipe('dasia', 'varia')
recipes('dasiaoxia').addRecipe('dasia', 'oxia')
recipes('dasiaperispomeni').addRecipe('dasia', 'perispomeni')
recipes('psilivaria').addRecipe('psili', 'varia')
recipes('psilioxia').addRecipe('psili', 'oxia')
recipes('psiliperispomeni').addRecipe('psili', 'perispomeni')
recipes('koronis').addRecipe('psili')
recipes('dialytikaperispomeni').addRecipe('dieresiscomb', 'perispomeni')


# Armenian
recipes('ayb-arm').addRecipe('seh-arm decompose', 'seh-arm decompose')
recipes('ben-arm').addRecipe('vo-arm decompose', 'p decompose', 'macroncomb decompose')
recipes('gim-arm').addRecipe('q decompose', 'macroncomb decompose')
recipes('da-arm').addRecipe('vo-arm decompose', 'macroncomb decompose')
recipes('ech-arm').addRecipe('seh-arm decompose', 'l decompose', 'macroncomb decompose')
recipes('za-arm').addRecipe('q decompose', 'macroncomb decompose')
recipes('eh-arm').addRecipe('l decompose', 'macroncomb decompose', 'e decompose')
recipes('et-arm').addRecipe('reh-arm', 'macroncomb decompose')
recipes('to-arm').addRecipe('p decompose', 'e decompose')
recipes('zhe-arm').addRecipe('eth decompose', 'd decompose', 'macroncomb decompose')
recipes('ini-arm').addRecipe('ho-arm decompose')
recipes('liwn-arm').addRecipe('za-arm decompose', 'idotless decompose')
recipes('xeh-arm').addRecipe('ho-arm decompose', 'seh-arm decompose')
recipes('ca-arm').addRecipe('zhe-arm decompose')
recipes('ken-arm').addRecipe('seh-arm decompose', 'l decompose', 'q decompose')
recipes('ho-arm').addRecipe('ho-arm decompose')
recipes('ja-arm').addRecipe('a decompose', 'eh-arm decompose')
recipes('ghad-arm').addRecipe('vo-arm decompose', 'liwn-arm decompose')
recipes('cheh-arm').addRecipe('ja-arm decompose', 'macroncomb decompose')
recipes('men-arm').addRecipe('seh-arm decompose')
recipes('now-arm').addRecipe('seh-arm decompose', 'eh-arm decompose')
recipes('sha-arm').addRecipe('two decompose')
recipes('vo-arm').addRecipe('n decompose')
recipes('peh-arm').addRecipe('ayb-arm decompose')
recipes('ra-arm').addRecipe('vo-arm decompose', 'macroncomb decompose')
recipes('seh-arm').addRecipe('u decompose')
recipes('vew-arm').addRecipe('seh-arm decompose', 'za-arm decompose', 'd decompose')
recipes('tiwn-arm').addRecipe('seh-arm decompose', 'vo-arm decompose')
recipes('reh-arm').addRecipe('vo-arm decompose')
recipes('co-arm').addRecipe('q decompose', 'e decompose')
recipes('yiwn-arm').addRecipe('liwn-arm decompose')
recipes('piwr-arm').addRecipe('tiwn-arm decompose', 'l decompose')
recipes('oh-arm').addRecipe('o decompose')
recipes('keh-arm').addRecipe('p decompose', 'macroncomb decompose')
recipes('jheh-arm').addRecipe('sha-arm decompose')
recipes('cha-arm').addRecipe('sha-arm decompose', 's decompose')
recipes('feh-arm').addRecipe('B decompose', 's decompose')
recipes('Seh-arm').addRecipe('U decompose')
recipes('Reh-arm').addRecipe('Vo-arm decompose')
recipes('Ayb-arm').addRecipe('Seh-arm', 'eh-arm decompose')
recipes('Ben-arm').addRecipe('Reh-arm', '_part.bar')
recipes('Da-arm').addRecipe('Ben-arm decompose')
recipes('Gim-arm').addRecipe('Ben-arm decompose')
recipes('Ech-arm').addRecipe('Ben-arm decompose')
recipes('Eh-arm').addRecipe('eh-arm decompose', 'Ech-arm decompose')
recipes('Et-arm').addRecipe('Ben-arm decompose')
recipes('To-arm').addRecipe('Ben-arm decompose', 'to-arm decompose')
recipes('Zhe-arm').addRecipe('Gim-arm decompose')
recipes('Ini-arm').addRecipe('Reh-arm decompose')
recipes('Liwn-arm').addRecipe('Eh-arm decompose')
recipes('Xeh-arm').addRecipe('Eh-arm decompose', 'Seh-arm decompose')
recipes('Ken-arm').addRecipe('Ini-arm decompose')
recipes('Ghad-arm').addRecipe('Da-arm decompose')
recipes('Vo-arm').addRecipe('Seh-arm decompose')
recipes('Za-arm').addRecipe('nine decompose', 'Eh-arm decompose')
recipes('Ca-arm').addRecipe('O decompose', 'Liwn-arm decompose')
recipes('Ho-arm').addRecipe('Liwn-arm decompose', 'cheh-arm decompose')
recipes('Men-arm').addRecipe('Da-arm decompose', 'Seh-arm')
recipes('Now-arm').addRecipe('Ghad-arm decompose')
recipes('Ra-arm').addRecipe('_part.Vo-arm', '_part.bar')
recipes('Ra-arm').addRecipe('Vo-arm', 'Da-arm decompose')
recipes('Oh-arm').addRecipe('O decompose')
recipes('Piwr-arm').addRecipe('Phi decompose')
recipes('Peh-arm').addRecipe('Da-arm decompose')
recipes('Vew-arm').addRecipe('Ken-arm', 'Ghad-arm decompose')
recipes('Yi-arm').addRecipe('B decompose')
recipes('Keh-arm').addRecipe('Gim-arm decompose')
recipes('Co-arm').addRecipe('o decompose')
recipes('Yiwn-arm').addRecipe('Xeh-arm decompose')
recipes('Jheh-arm').addRecipe('Za-arm decompose')
recipes('Feh-arm').addRecipe('feh-arm decompose')
recipes('Sha-arm').addRecipe('Ech-arm decompose', 'tilde decompose')
recipes('Ja-arm').addRecipe('Sha-arm decompose')
recipes('Cha-arm').addRecipe('Ja-arm decompose', 'Yiwn-arm decompose')
recipes('Cheh-arm').addRecipe('cheh-arm decompose')
recipes('ech_yiwn-arm').addRecipe('ken-arm decompose', 'yiwn-arm decompose')
recipes('apostrophe-arm').addRecipe('quoteright')
recipes('period-arm').addRecipe('colon')
recipes('ringhalfleft-arm').addRecipe('brevecomb rotate_90 flip_vertical')
recipes('emphasis-arm').addRecipe('acute decompose')
recipes('exclam-arm').addRecipe('tilde decompose')
recipes('comma-arm').addRecipe('emphasis-arm flip_horizontal')
recipes('dram-arm').addRecipe('Da-arm decompose')
recipes('hyphen-arm').addRecipe('quotesingle rotate_90', 'hyphen')
recipes('question-arm').addRecipe('brevecomb flip_vertical decompose')
recipes('abbreviation-arm').addRecipe('question-arm rotate_180 decompose')
recipes('leftFacingEternity-arm').addRecipe('rightFacingEternity-arm flip_horizontal')
recipes('rightFacingEternity-arm').addRecipe('leftFacingEternity-arm flip_horizontal')


recipes('za-arm.long').addRecipe('za-arm decompose')
recipes('liwn-arm.long').addRecipe('liwn-arm decompose')
recipes('ghad-arm.long').addRecipe('ghad-arm decompose')
recipes('vew-arm.long').addRecipe('vew-arm decompose')
recipes('ben-arm.short').addRecipe('ben-arm decompose')
recipes('et-arm.short').addRecipe('et-arm decompose')
recipes('ini-arm.short').addRecipe('ini-arm decompose')
recipes('xeh-arm.short').addRecipe('xeh-arm decompose')
recipes('yi-arm.short').addRecipe('yi-arm decompose')
recipes('reh-arm.short').addRecipe('reh-arm decompose')
recipes('co-arm.short').addRecipe('co-arm decompose')


# Arabic
recipes('hah-ar.fina').addRecipe('hah-ar')
recipes('hah-ar.medi').addRecipe('hah-ar.init')
recipes('hamzabelowKasra-ar').addRecipe('hamzabelow-ar', 'kasra-ar')
recipes('hamzabelowKasratan-ar').addRecipe('hamzabelow-ar', 'kasratan-ar')
recipes('shaddaAlefabove-ar').addRecipe('shadda-ar', 'alefabove-ar')
recipes('shaddaDamma-ar').addRecipe('shadda-ar', 'damma-ar')
recipes('shaddaDammatan-ar').addRecipe('shadda-ar', 'dammatan-ar')
recipes('shaddaKasratan-ar').addRecipe('fathatan-ar', 'shadda-ar')

# Devanagari
recipes('k-deva').addRecipe('ka-deva decompose')
recipes('kh-deva').addRecipe('kha-deva decompose')
recipes('g-deva').addRecipe('ga-deva decompose')
recipes('gh-deva').addRecipe('gha-deva decompose')
recipes('ng-deva').addRecipe('nga-deva', 'halant-deva')
recipes('c-deva').addRecipe('ca-deva decompose')
recipes('ch-deva').addRecipe('cha-deva', 'halant-deva')
recipes('j-deva').addRecipe('ja-deva decompose')
recipes('jh-deva').addRecipe('jha-deva decompose')
recipes('ny-deva').addRecipe('nya-deva decompose')
recipes('nn-deva').addRecipe('nna-deva decompose')
recipes('t-deva').addRecipe('ta-deva decompose')
recipes('th-deva').addRecipe('tha-deva decompose')
recipes('dh-deva').addRecipe('dha-deva decompose')
recipes('n-deva').addRecipe('na-deva decompose')
recipes('p-deva').addRecipe('pa-deva decompose')
recipes('ph-deva').addRecipe('pha-deva decompose')
recipes('b-deva').addRecipe('ba-deva decompose')
recipes('bh-deva').addRecipe('bha-deva decompose')
recipes('m-deva').addRecipe('ma-deva decompose')
recipes('y-deva').addRecipe('ya-deva decompose')
recipes('rr-deva').addRecipe('rra-deva decompose')
recipes('l-deva').addRecipe('la-deva decompose')
recipes('ll-deva').addRecipe('lla-deva decompose')
recipes('v-deva').addRecipe('va-deva decompose')
recipes('sh-deva').addRecipe('sha-deva decompose')
recipes('ss-deva').addRecipe('ssa-deva decompose')
recipes('s-deva').addRecipe('sa-deva decompose')
recipes('h-deva').addRecipe('ha-deva decompose')
recipes('tt-deva').addRecipe('tta-deva', 'halant-deva')
recipes('tth-deva').addRecipe('ttha-deva', 'halant-deva')
recipes('dd-deva').addRecipe('dda-deva', 'halant-deva')
recipes('ddh-deva').addRecipe('ddha-deva', 'halant-deva')
recipes('d-deva').addRecipe('da-deva', 'halant-deva')
recipes('gg-deva').addRecipe('g-deva')
recipes('jj-deva').addRecipe('j-deva')
recipes('ddd-deva').addRecipe('dd-deva')
recipes('bb-deva').addRecipe('b-deva')

recipes('ng_nukta-deva').addRecipe('nga-deva', 'nukta-deva', 'halant-deva')
recipes('ch_nukta-deva').addRecipe('cha-deva', 'nukta-deva', 'halant-deva')
recipes('tt_nukta-deva').addRecipe('tta-deva', 'nukta-deva', 'halant-deva')
recipes('tth_nukta-deva').addRecipe('ttha-deva', 'nukta-deva', 'halant-deva')
recipes('dd_nukta-deva').addRecipe('dda-deva', 'nukta-deva', 'halant-deva')
recipes('ddh_nukta-deva').addRecipe('ddha-deva', 'nukta-deva', 'halant-deva')
recipes('bb_nukta-deva').addRecipe('bba-deva', 'nukta-deva', 'halant-deva')
recipes('ddd_nukta-deva').addRecipe('ddda-deva', 'nukta-deva', 'halant-deva')
recipes('gg_nukta-deva').addRecipe('gga-deva', 'nukta-deva', 'halant-deva')
recipes('jj_nukta-deva').addRecipe('jja-deva', 'nukta-deva', 'halant-deva')

recipes('ka_halant_ra_halant-deva').addRecipe('k-deva', 'ka_halant_ra-deva decompose')
recipes('kha_halant_ra_halant-deva').addRecipe('kh-deva', 'kha_halant_ra-deva decompose')
recipes('ga_halant_ra_halant-deva').addRecipe('g-deva', 'ga_halant_ra-deva decompose')
recipes('gha_halant_ra_halant-deva').addRecipe('gh-deva', 'gha_halant_ra-deva decompose')
recipes('nga_halant_ra_halant-deva').addRecipe('nga-deva', 'rakar-deva', 'halant-deva')
recipes('ca_halant_ra_halant-deva').addRecipe('c-deva', 'ca_halant_ra-deva decompose')
recipes('cha_halant_ra_halant-deva').addRecipe('cha-deva', 'rakar-deva', 'halant-deva')
recipes('ja_halant_ra_halant-deva').addRecipe('j-deva', 'ja_halant_ra-deva decompose')
recipes('jha_halant_ra_halant-deva').addRecipe('jh-deva', 'jha_halant_ra-deva decompose')
recipes('nya_halant_ra_halant-deva').addRecipe('ny-deva', 'nya_halant_ra-deva decompose')
recipes('tta_halant_ra_halant-deva').addRecipe('tta-deva', 'rakar-deva', 'halant-deva')
recipes('ttha_halant_ra_halant-deva').addRecipe('ttha-deva', 'rakar-deva', 'halant-deva')
recipes('dda_halant_ra_halant-deva').addRecipe('dda-deva', 'rakar-deva', 'halant-deva')
recipes('ddha_halant_ra_halant-deva').addRecipe('ddha-deva', 'rakar-deva', 'halant-deva')
recipes('nna_halant_ra_halant-deva').addRecipe('nn-deva', 'nna_halant_ra-deva decompose')
recipes('ta_halant_ra_halant-deva').addRecipe('t-deva', 'ta_halant_ra-deva decompose')
recipes('tha_halant_ra_halant-deva').addRecipe('th-deva', 'tha_halant_ra-deva decompose')
recipes('da_halant_ra_halant-deva').addRecipe('d-deva', 'da_halant_ra-deva decompose')
recipes('dha_halant_ra_halant-deva').addRecipe('dh-deva', 'dha_halant_ra-deva decompose')
recipes('na_halant_ra_halant-deva').addRecipe('n-deva', 'na_halant_ra-deva decompose')
recipes('pa_halant_ra_halant-deva').addRecipe('p-deva', 'pa_halant_ra-deva decompose')
recipes('pha_halant_ra_halant-deva').addRecipe('ph-deva', 'pha_halant_ra-deva decompose')
recipes('ba_halant_ra_halant-deva').addRecipe('b-deva', 'ba_halant_ra-deva decompose')
recipes('bha_halant_ra_halant-deva').addRecipe('bh-deva', 'bha_halant_ra-deva decompose')
recipes('ma_halant_ra_halant-deva').addRecipe('m-deva', 'ma_halant_ra-deva decompose')
recipes('ya_halant_ra_halant-deva').addRecipe('y-deva', 'ya_halant_ra-deva decompose')
recipes('ra_halant_ra_halant-deva').addRecipe('r-deva', 'ra_halant_ra-deva decompose')
recipes('la_halant_ra_halant-deva').addRecipe('l-deva', 'la_halant_ra-deva decompose')
recipes('lla_halant_ra_halant-deva').addRecipe('ll-deva', 'rakar-deva')
recipes('va_halant_ra_halant-deva').addRecipe('v-deva', 'va_halant_ra-deva decompose')
recipes('sha_halant_ra_halant-deva').addRecipe('sh-deva', 'sha_halant_ra-deva decompose')
recipes('ssa_halant_ra_halant-deva').addRecipe('ss-deva', 'ssa_halant_ra-deva decompose')
recipes('sa_halant_ra_halant-deva').addRecipe('s-deva', 'sa_halant_ra-deva decompose')
recipes('ha_halant_ra_halant-deva').addRecipe('h-deva', 'ha_halant_ra-deva decompose')

recipes('ka_nukta_halant_ra_halant-deva').addRecipe('ka_halant_ra_halant-deva', 'nukta-deva')
recipes('kha_nukta_halant_ra_halant-deva').addRecipe('kha_halant_ra_halant-deva', 'nukta-deva')
recipes('ga_nukta_halant_ra_halant-deva').addRecipe('ga_halant_ra_halant-deva', 'nukta-deva')
recipes('ja_nukta_halant_ra_halant-deva').addRecipe('ja_halant_ra_halant-deva', 'nukta-deva')
recipes('dda_nukta_halant_ra_halant-deva').addRecipe('dda_halant_ra_halant-deva', 'nukta-deva')
recipes('ddha_nukta_halant_ra_halant-deva').addRecipe('ddha_halant_ra_halant-deva', 'nukta-deva')
recipes('pha_nukta_halant_ra_halant-deva').addRecipe('pha_halant_ra_halant-deva', 'nukta-deva')
recipes('ya_nukta_halant_ra_halant-deva').addRecipe('ya_halant_ra_halant-deva', 'nukta-deva')
recipes('gha_nukta_halant_ra_halant-deva').addRecipe('gha_halant_ra_halant-deva', 'nukta-deva')
recipes('nga_nukta_halant_ra_halant-deva').addRecipe('nga_halant_ra_halant-deva', 'nukta-deva')
recipes('ca_nukta_halant_ra_halant-deva').addRecipe('ca_halant_ra_halant-deva', 'nukta-deva')
recipes('cha_nukta_halant_ra_halant-deva').addRecipe('cha_halant_ra_halant-deva', 'nukta-deva')
recipes('jha_nukta_halant_ra_halant-deva').addRecipe('jha_halant_ra_halant-deva', 'nukta-deva')
recipes('nya_nukta_halant_ra_halant-deva').addRecipe('nya_halant_ra_halant-deva', 'nukta-deva')
recipes('tta_nukta_halant_ra_halant-deva').addRecipe('tta_halant_ra_halant-deva', 'nukta-deva')
recipes('ttha_nukta_halant_ra_halant-deva').addRecipe('ttha_halant_ra_halant-deva', 'nukta-deva')
recipes('nna_nukta_halant_ra_halant-deva').addRecipe('nna_halant_ra_halant-deva', 'nukta-deva')
recipes('ta_nukta_halant_ra_halant-deva').addRecipe('ta_halant_ra_halant-deva', 'nukta-deva')
recipes('tha_nukta_halant_ra_halant-deva').addRecipe('tha_halant_ra_halant-deva', 'nukta-deva')
recipes('da_nukta_halant_ra_halant-deva').addRecipe('da_halant_ra_halant-deva', 'nukta-deva')
recipes('dha_nukta_halant_ra_halant-deva').addRecipe('dha_halant_ra_halant-deva', 'nukta-deva')
recipes('pa_nukta_halant_ra_halant-deva').addRecipe('pa_halant_ra_halant-deva', 'nukta-deva')
recipes('ba_nukta_halant_ra_halant-deva').addRecipe('ba_halant_ra_halant-deva', 'nukta-deva')
recipes('bha_nukta_halant_ra_halant-deva').addRecipe('bha_halant_ra_halant-deva', 'nukta-deva')
recipes('ma_nukta_halant_ra_halant-deva').addRecipe('ma_halant_ra_halant-deva', 'nukta-deva')
recipes('la_nukta_halant_ra_halant-deva').addRecipe('la_halant_ra_halant-deva', 'nukta-deva')
recipes('va_nukta_halant_ra_halant-deva').addRecipe('va_halant_ra_halant-deva', 'nukta-deva')
recipes('sha_nukta_halant_ra_halant-deva').addRecipe('sha_halant_ra_halant-deva', 'nukta-deva')
recipes('ssa_nukta_halant_ra_halant-deva').addRecipe('ssa_halant_ra_halant-deva', 'nukta-deva')
recipes('sa_nukta_halant_ra_halant-deva').addRecipe('sa_halant_ra_halant-deva', 'nukta-deva')
recipes('ha_nukta_halant_ra_halant-deva').addRecipe('ha_halant_ra_halant-deva', 'nukta-deva')
recipes('j_ny-deva').addRecipe('j_nya-deva decompose')
recipes('jha-deva.loclNEP').addRecipe('bha-deva decompose', 'ka-deva decompose')
recipes('jh-deva.loclNEP').addRecipe('k-deva decompose', 'jha-deva.loclNEP decompose')
recipes('fa_ra-deva').addRecipe('pha_ra-deva', 'nukta-deva')
recipes('f_ra-deva').addRecipe('ph_ra-deva', 'nukta-deva')
recipes('ghha_ra-deva').addRecipe('ga_ra-deva', 'nukta-deva')
recipes('ghh_ra-deva').addRecipe('g_ra-deva', 'nukta-deva')
recipes('khha_ra-deva').addRecipe('kha_ra-deva', 'nukta-deva')
recipes('khh_ra-deva').addRecipe('kh_ra-deva', 'nukta-deva')
recipes('nnna_ra-deva').addRecipe('na_ra-deva', 'nukta-deva')
recipes('nnn_ra-deva').addRecipe('n_ra-deva', 'nukta-deva')
recipes('qa_ra-deva').addRecipe('ka_ra-deva', 'nukta-deva')
recipes('q_ra-deva').addRecipe('k_ra-deva', 'nukta-deva')
recipes('yya_ra-deva').addRecipe('ya_ra-deva', 'nukta-deva')
recipes('yy_ra-deva').addRecipe('y_ra-deva', 'nukta-deva')
recipes('za_ra-deva').addRecipe('ja_ra-deva', 'nukta-deva')
recipes('z_ra-deva').addRecipe('j_ra-deva', 'nukta-deva')
recipes('ka_ra-deva.loclNEP').addRecipe('ka_ra-deva decompose', 'halant-deva decompose')

recipes('z_ra-deva').addRecipe('j_ra-deva', 'nukta-deva')
recipes('yy_ra-deva').addRecipe('y_ra-deva', 'nukta-deva')
recipes('zha-deva').addRecipe('ja-deva', 'nukta-deva', 'nukta-deva', 'nukta-deva')


recipes('aa-deva').addRecipe('a-deva', 'aaMatra-deva')
recipes('oe-deva').addRecipe('a-deva', 'oeMatra-deva')
recipes('ooeMatra-deva').addRecipe('aaMatra-deva', 'oeMatra-deva')
recipes('ooe-deva').addRecipe('a-deva', 'ooeMatra-deva')
recipes('o-deva').addRecipe('a-deva', 'oMatra-deva')
recipes('aShort-deva').addRecipe('a-deva', 'eShortMatra-deva')
recipes('oShort-deva').addRecipe('a-deva', 'oShortMatra-deva')
recipes('aw-deva').addRecipe('a-deva', 'awMatra-deva')
recipes('uue-deva').addRecipe('a-deva', 'uueMatra-deva')
recipes('ue-deva').addRecipe('a-deva', 'ueMatra-deva')


recipes('tonebarextrahighmod_tonebarextrahighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to5A', '_part.tonePart1to1')
recipes('tonebarextrahighmod_tonebarextrahighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to1')
recipes('tonebarextrahighmod_tonebarextrahighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart1to1')
recipes('tonebarextrahighmod_tonebarextrahighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart1to1')
recipes('tonebarextrahighmod_tonebarextralowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart5to1A', '_part.tonePart1to5B')
recipes('tonebarextrahighmod_tonebarextralowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to5B')
recipes('tonebarextrahighmod_tonebarextralowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to5B')
recipes('tonebarextrahighmod_tonebarextralowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to5B')
recipes('tonebarextrahighmod_tonebarextralowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to5B')
recipes('tonebarextrahighmod_tonebarhighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to2B')
recipes('tonebarextrahighmod_tonebarhighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart1to2B')
recipes('tonebarextrahighmod_tonebarhighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to2B')
recipes('tonebarextrahighmod_tonebarhighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart1to2B')
recipes('tonebarextrahighmod_tonebarhighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to2B')
recipes('tonebarextrahighmod_tonebarlowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to4B')
recipes('tonebarextrahighmod_tonebarlowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to4B')
recipes('tonebarextrahighmod_tonebarlowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to4B')
recipes('tonebarextrahighmod_tonebarlowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to4B')
recipes('tonebarextrahighmod_tonebarlowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to4B')
recipes('tonebarextrahighmod_tonebarmidmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to3B')
recipes('tonebarextrahighmod_tonebarmidmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart1to3B')
recipes('tonebarextrahighmod_tonebarmidmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to3B')
recipes('tonebarextrahighmod_tonebarmidmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to3B')
recipes('tonebarextrahighmod_tonebarmidmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to3B')
recipes('tonebarextralowmod_tonebarextrahighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart5to1B')
recipes('tonebarextralowmod_tonebarextrahighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to5A', '_part.tonePart5to1B')
recipes('tonebarextralowmod_tonebarextrahighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart5to1B')
recipes('tonebarextralowmod_tonebarextrahighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart5to1B')
recipes('tonebarextralowmod_tonebarextrahighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart5to1B')
recipes('tonebarextralowmod_tonebarextralowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart5to1A', '_part.tonePart1to1')
recipes('tonebarextralowmod_tonebarextralowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to1')
recipes('tonebarextralowmod_tonebarextralowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to1')
recipes('tonebarextralowmod_tonebarextralowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to1')
recipes('tonebarextralowmod_tonebarhighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart4to1B')
recipes('tonebarextralowmod_tonebarhighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart4to1B')
recipes('tonebarextralowmod_tonebarhighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart4to1B')
recipes('tonebarextralowmod_tonebarhighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart4to1B')
recipes('tonebarextralowmod_tonebarhighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart4to1B')
recipes('tonebarextralowmod_tonebarlowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart2to1B')
recipes('tonebarextralowmod_tonebarlowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart2to1B')
recipes('tonebarextralowmod_tonebarlowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart2to1B')
recipes('tonebarextralowmod_tonebarlowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart2to1B')
recipes('tonebarextralowmod_tonebarlowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart2to1B')
recipes('tonebarextralowmod_tonebarmidmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart3to1B')
recipes('tonebarextralowmod_tonebarmidmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart3to1B')
recipes('tonebarextralowmod_tonebarmidmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart3to1B')
recipes('tonebarextralowmod_tonebarmidmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart3to1B')
recipes('tonebarextralowmod_tonebarmidmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart3to1B')
recipes('tonebarhighmod_tonebarextrahighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart2to1B')
recipes('tonebarhighmod_tonebarextrahighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to5A', '_part.tonePart2to1B')
recipes('tonebarhighmod_tonebarextrahighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart2to1B')
recipes('tonebarhighmod_tonebarextrahighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart2to1B')
recipes('tonebarhighmod_tonebarextrahighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart2to1B')
recipes('tonebarhighmod_tonebarextralowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart5to1A', '_part.tonePart1to4B')
recipes('tonebarhighmod_tonebarextralowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to4B')
recipes('tonebarhighmod_tonebarextralowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to4B')
recipes('tonebarhighmod_tonebarextralowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to4B')
recipes('tonebarhighmod_tonebarextralowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to4B')
recipes('tonebarhighmod_tonebarhighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to1')
recipes('tonebarhighmod_tonebarhighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart1to1')
recipes('tonebarhighmod_tonebarhighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart1to1')
recipes('tonebarhighmod_tonebarhighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to1')
recipes('tonebarhighmod_tonebarlowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to3B')
recipes('tonebarhighmod_tonebarlowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to3B')
recipes('tonebarhighmod_tonebarlowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to3B')
recipes('tonebarhighmod_tonebarlowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to3B')
recipes('tonebarhighmod_tonebarlowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to3B')
recipes('tonebarhighmod_tonebarmidmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to2B')
recipes('tonebarhighmod_tonebarmidmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart1to2B')
recipes('tonebarhighmod_tonebarmidmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to2B')
recipes('tonebarhighmod_tonebarmidmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to2B')
recipes('tonebarhighmod_tonebarmidmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarextrahighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart4to1B')
recipes('tonebarlowmod_tonebarextrahighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to5A', '_part.tonePart4to1B')
recipes('tonebarlowmod_tonebarextrahighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart4to1B')
recipes('tonebarlowmod_tonebarextrahighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart4to1B')
recipes('tonebarlowmod_tonebarextrahighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart4to1B')
recipes('tonebarlowmod_tonebarextralowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart5to1A', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarextralowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarextralowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarextralowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarextralowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarhighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart3to1B')
recipes('tonebarlowmod_tonebarhighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart3to1B')
recipes('tonebarlowmod_tonebarhighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart3to1B')
recipes('tonebarlowmod_tonebarhighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart3to1B')
recipes('tonebarlowmod_tonebarhighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart3to1B')
recipes('tonebarlowmod_tonebarlowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to1')
recipes('tonebarlowmod_tonebarlowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to1')
recipes('tonebarlowmod_tonebarlowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to1')
recipes('tonebarlowmod_tonebarlowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to1')
recipes('tonebarlowmod_tonebarmidmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart2to1B')
recipes('tonebarlowmod_tonebarmidmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart2to1B')
recipes('tonebarlowmod_tonebarmidmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart2to1B')
recipes('tonebarlowmod_tonebarmidmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart2to1B')
recipes('tonebarlowmod_tonebarmidmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarextrahighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart3to1B')
recipes('tonebarmidmod_tonebarextrahighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to5A', '_part.tonePart3to1B')
recipes('tonebarmidmod_tonebarextrahighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart3to1B')
recipes('tonebarmidmod_tonebarextrahighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart3to1B')
recipes('tonebarmidmod_tonebarextrahighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart3to1B')
recipes('tonebarmidmod_tonebarextralowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart5to1A', '_part.tonePart1to3B')
recipes('tonebarmidmod_tonebarextralowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to3B')
recipes('tonebarmidmod_tonebarextralowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to3B')
recipes('tonebarmidmod_tonebarextralowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to3B')
recipes('tonebarmidmod_tonebarextralowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to3B')
recipes('tonebarmidmod_tonebarhighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarhighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to4A', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarhighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarhighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarhighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarlowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart4to1A', '_part.tonePart1to2B')
recipes('tonebarmidmod_tonebarlowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to2B')
recipes('tonebarmidmod_tonebarlowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to2B')
recipes('tonebarmidmod_tonebarlowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to1', '_part.tonePart1to2B')
recipes('tonebarmidmod_tonebarlowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to2B')
recipes('tonebarmidmod_tonebarmidmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart3to1A', '_part.tonePart1to1')
recipes('tonebarmidmod_tonebarmidmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to3A', '_part.tonePart1to1')
recipes('tonebarmidmod_tonebarmidmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart2to1A', '_part.tonePart1to1')
recipes('tonebarmidmod_tonebarmidmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to2A', '_part.tonePart1to1')
recipes('tonebarextrahighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to5B')
recipes('tonebarextrahighmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart1to2B')
recipes('tonebarextrahighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to4B')
recipes('tonebarextrahighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to3B')
recipes('tonebarextralowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart5to1B')
recipes('tonebarextralowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart4to1B')
recipes('tonebarextralowmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart2to1B')
recipes('tonebarextralowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart3to1B')
recipes('tonebarhighmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart2to1B')
recipes('tonebarhighmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to4B')
recipes('tonebarhighmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to3B')
recipes('tonebarhighmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart4to1B')
recipes('tonebarlowmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to2B')
recipes('tonebarlowmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart3to1B')
recipes('tonebarlowmod_tonebarmidmod').addRecipe('toneStem', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarextrahighmod').addRecipe('toneStem', '_part.tonePart3to1B')
recipes('tonebarmidmod_tonebarextralowmod').addRecipe('toneStem', '_part.tonePart1to3B')
recipes('tonebarmidmod_tonebarhighmod').addRecipe('toneStem', '_part.tonePart2to1B')
recipes('tonebarmidmod_tonebarlowmod').addRecipe('toneStem', '_part.tonePart1to2B')


# Hebrew
recipes('upperdot-hb').addRecipe('holam-hb')
recipes('siluqleft-hb').addRecipe('qamats-hb decompose')
recipes('judeospanishvarika-hb').addRecipe('brevecomb')


Glyphs.font.disableUpdateInterface()

for g in [x.parent for x in Glyphs.font.selectedLayers]:
    for l in g.layers:
        if force_build:
            if recipes.has_recipe(g.name, italic=recipes.italic_angle(l)):
                l.paths = []
                l.components = []
                l.anchors = []
            else:
                recipes.addComponents(l)

        empty = not l.paths
        if empty:
            empty = not l.components

        if empty:
            print(g.name, recipes.has_recipe(g.name))
            if not recipes.has_recipe(g.name, italic=recipes.italic_angle(l)):
                recipes.addComponents(l)
                continue

            this_recipe = recipes(g.name, italic=recipes.italic_angle(l))

            for ingredient in this_recipe:
                new_comp = GSComponent(ingredient.name, NSPoint(0, 0))
                new_comp.automaticAlignment = False
                parent_layer = Glyphs.font.glyphs[ingredient.name].layers[l.associatedMasterId]
                l.width = parent_layer.width

                l.components.append(new_comp)

                if ingredient.rotate_90:
                    this_rotation = -90
                elif ingredient.rotate_180:
                    this_rotation = 180
                elif ingredient.rotate_270:
                    this_rotation = 90
                else:
                    this_rotation = 0

                if ingredient.flip_horizontal and ingredient.flip_vertical:
                    this_scale_x = -1
                    this_scale_y = -1
                elif ingredient.flip_horizontal:
                    this_scale_x = -1
                    this_scale_y = 1
                elif ingredient.flip_vertical:
                    this_scale_x = 1
                    this_scale_y = -1
                else:
                    this_scale_x = 1
                    this_scale_y = 1

                if abs(this_rotation) == 90:
                    this_scale_x, this_scale_y = (this_scale_y, this_scale_x)

                new_comp.setScaleX_scaleY_rotation_(this_scale_x, this_scale_y, this_rotation)

                offset_x = parent_layer.bounds.origin.x - new_comp.bounds.origin.x
                offset_y = parent_layer.bounds.origin.y - new_comp.bounds.origin.y
                new_comp.setPosition_(NSPoint(offset_x, offset_y))

                if ingredient.accent_top:
                    new_coords = recipes.transform_position_y(
                        new_comp.bounds.origin,
                        recipes.accent_tops.get(l.associatedMasterId),
                        italic_angle=recipes.italic_angle(l)
                    )
                elif ingredient.accent_bottom:
                    new_coords = recipes.transform_position_y(
                        NSPoint(new_comp.bounds.origin.x + new_comp.bounds.size.width, new_comp.bounds.origin.y + new_comp.bounds.size.height),
                        recipes.accent_bottoms.get(l.associatedMasterId),
                        italic_angle=recipes.italic_angle(l)
                    )
                else:
                    new_coords = NSPoint(0, 0)

                new_comp.applyTransform((1, 0, 0, 1, new_coords.x, new_coords.y))

                if new_comp.position == NSPoint(0, 0) and not ingredient.disable_alignment:
                    new_comp.automaticAlignment = True

                if ingredient.decompose:
                    try:
                        l.components[-1].decompose()
                    except Exception as e:
                        print(e)

            l.syncMetrics()
            l.anchors = []
    g.updateGlyphInfo()


Glyphs.font.enableUpdateInterface()
