# MenuTitle: Set Metric Keys for Selected
# -*- coding: utf-8 -*-
__doc__ = """
Sets the left/right/width to the predefined key.
"""

Glyphs.clearLog()
# Glyphs.showMacroWindow()


class mKeys:
    def __init__(self, font):
        self.glyphs = {}
        self.font = font
        self.isItalic = self.font.fontMasterAtIndex_(0).italicAngle != 0

    class glyphMetrics:
        def __init__(self, gname):
            self.name = gname
            self.left = None
            self.right = None
            self.width = None

    def __call__(self, gname, **kwargs):
        g = self.font.glyphForName_(gname)
        if g:
            ng = self.glyphMetrics(gname)

            if self.isItalic:
                ng.left = kwargs.get('italic_left', kwargs.get('left'))
                ng.right = kwargs.get('italic_right', kwargs.get('right'))
                ng.width = kwargs.get('italic_width', kwargs.get('width'))
            else:
                ng.left = kwargs.get('left')
                ng.right = kwargs.get('right')
                ng.width = kwargs.get('width')

            self.glyphs[gname] = ng

            sc_name = self.make_smallcap_name(gname)
            if gname[0].isupper() and self.font.glyphForName_(sc_name):
                ngsc = self.glyphMetrics(sc_name)
                if ng.right is not None:
                    ngsc.right = self.make_smallcap_name(ng.right)
                if ng.left is not None:
                    ngsc.left = self.make_smallcap_name(ng.left)
                if ng.width is not None:
                    ngsc.width = self.make_smallcap_name(ng.width)

                self.glyphs[ngsc.name] = ngsc

    def make_smallcap_name(self, gn):
        arbitrary_initial_letters_len = 3
        return gn[:arbitrary_initial_letters_len].lower() + gn[arbitrary_initial_letters_len:] + '.sc'


grouping = mKeys(Glyphs.font)
grouping('.notdef', left='=0', right='=0')
grouping('A', left='A', right='A')
grouping('AE', left='AE', right='E')
grouping('AEacute', left='AE', right='E')
grouping('Aacute', left='A', right='A')
grouping('Abreve', left='A', right='A')
grouping('Abreveacute', left='A', right='A')
grouping('Abrevedotbelow', left='A', right='A')
grouping('Abrevegrave', left='A', right='A')
grouping('Abrevehookabove', left='A', right='A')
grouping('Abrevetilde', left='A', right='A')
grouping('Acaron', left='A', right='A')
grouping('Acircumflex', left='A', right='A')
grouping('Acircumflexacute', left='A', right='A')
grouping('Acircumflexdotbelow', left='A', right='A')
grouping('Acircumflexgrave', left='A', right='A')
grouping('Acircumflexhookabove', left='A', right='A')
grouping('Acircumflextilde', left='A', right='A')
grouping('Adieresis', left='A', right='A')
grouping('Adotbelow', left='A', right='A')
grouping('Agrave', left='A', right='A')
grouping('Ahookabove', left='A', right='A')
grouping('Amacron', left='A', right='A')
grouping('Aogonek', left='A', right='A')
grouping('Aring', left='A', right='A')
grouping('Aringacute', left='A', right='A')
grouping('Atilde', left='A', right='A')
grouping('B', left='H', right='B')
grouping('C', left='O', right='C')
grouping('Cacute', left='C', right='C')
grouping('Ccaron', left='C', right='C')
grouping('Ccedilla', left='C', right='C')
grouping('Ccircumflex', left='C', right='C')
grouping('Cdotaccent', left='C', right='C')
grouping('D', left='H', right='O')
grouping('Dcaron', left='D', right='D')
grouping('Dcroat', left='Eth', right='D')
grouping('E', left='H', right='E')
grouping('Eacute', left='E', right='E')
grouping('Ebreve', left='E', right='E')
grouping('Ecaron', left='E', right='E')
grouping('Ecircumflex', left='E', width='E')
grouping('Ecircumflexacute', left='E', width='E')
grouping('Ecircumflexdotbelow', left='E', width='E')
grouping('Ecircumflexgrave', left='E', width='E')
grouping('Ecircumflexhookabove', left='E', width='E')
grouping('Ecircumflextilde', left='E', width='E')
grouping('Edieresis', left='E', width='E')
grouping('Edotaccent', left='E', width='E')
grouping('Edotbelow', left='E', width='E')
grouping('Egrave', left='E', width='E')
grouping('Ehookabove', left='E', width='E')
grouping('Emacron', left='E', width='E')
grouping('Eng', left='H', right='N')
grouping('Eogonek', left='E', right='E')
grouping('Eth', left='Eth', right='D')
grouping('Etilde', left='H', right='E')
grouping('F', left='H', right='F')
grouping('G', left='O', right='G')
grouping('Gbreve', left='G', right='G')
grouping('Gcircumflex', left='G', right='G')
grouping('Gcommaaccent', left='G', right='G')
grouping('Gdotaccent', left='G', right='G')
grouping('Germandbls', left='Germandbls', right='Germandbls')
grouping('H', left='H', right='H')
grouping('Hbar', left='H', right='H')
grouping('Hcircumflex', left='H', right='H')
grouping('I', left='H', right='H')
grouping('IJ', left='H', right='J')
grouping('Iacute', left='I', width='I')
grouping('Ibreve', left='I', right='I')
grouping('Icaron', left='I', right='I')
grouping('Icircumflex', left='I', right='I')
grouping('Idieresis', left='I', right='I')
grouping('Idotaccent', left='I', right='I')
grouping('Idotbelow', left='I', right='I')
grouping('Igrave', width='I', right='I')
grouping('Ihookabove', left='I', right='I')
grouping('Imacron', left='I', right='I')
grouping('Iogonek', left='I', right='I')
grouping('Itilde', left='I', right='I')
grouping('J', left='J', right='J')
grouping('Jcircumflex', left='J', right='J')
grouping('K', left='H', right='K')
grouping('Kcommaaccent', left='K', right='K')
grouping('L', left='H', right='L')
grouping('Lacute', left='L', right='L')
grouping('Lcaron', left='L', right='L')
grouping('Lcommaaccent', left='L', right='L')
grouping('Ldot', left='L', right='L')
grouping('Lslash', left='Lslash', right='L')
grouping('M', left='H', right='H')
grouping('N', left='H', right='N')
grouping('Nacute', left='N', right='N')
grouping('Napostrophe', left='quoteright', right='N')
grouping('napostrophe.sc', left='quoteright', right='n.sc')
grouping('Ncaron', left='N', right='N')
grouping('Ncommaaccent', left='N', right='N')
grouping('Ntilde', left='N', right='N')
grouping('O', left='O', right='O')
grouping('OE', left='O', right='E')
grouping('Oacute', left='O', right='O')
grouping('Obreve', left='O', right='O')
grouping('Ocaron', left='O', right='O')
grouping('Ocircumflex', left='O', right='O')
grouping('Ocircumflexacute', left='O', right='O')
grouping('Ocircumflexdotbelow', left='O', right='O')
grouping('Ocircumflexgrave', left='O', right='O')
grouping('Ocircumflexhookabove', left='O', width='O')
grouping('Ocircumflextilde', left='O', right='O')
grouping('Odieresis', left='O', right='O')
grouping('Odotbelow', left='O', right='O')
grouping('Ograve', left='O', right='O')
grouping('Ohookabove', left='O', right='O')
grouping('Ohorn', left='O', right='Ohorn')
grouping('Ohornacute', left='O', right='Ohorn')
grouping('Ohorndotbelow', left='O', right='Ohorn')
grouping('Ohorngrave', left='O', right='Ohorn')
grouping('Ohornhookabove', left='O', right='Ohorn')
grouping('Ohorntilde', left='O', right='Ohorn')
grouping('Ohungarumlaut', left='O', right='O')
grouping('Omacron', left='O', right='O')
grouping('Oslash', left='O', right='O')
grouping('Oslashacute', left='O', right='O')
grouping('Otilde', left='O', right='O')
grouping('P', left='H', right='P')
grouping('Q', left='O', right='O')
grouping('R', left='H', right='R')
grouping('Racute', left='R', right='R')
grouping('Rcaron', left='R', right='R')
grouping('Rcommaaccent', left='R', right='R')
grouping('S', left='S', right='S')
grouping('Sacute', left='S', right='S')
grouping('Scaron', left='S', right='S')
grouping('Scedilla', left='S', right='S')
grouping('Schwa', left='Schwa', right='O')
grouping('Scircumflex', left='S', right='S')
grouping('Scommaaccent', left='S', right='S')
grouping('T', left='T', right='T')
grouping('Tbar', left='T', right='T')
grouping('Tcaron', left='T', right='T')
grouping('Tcedilla', left='T', right='T')
grouping('Tcommaaccent', left='T', right='T')
grouping('Thorn', left='H', right='Thorn')
grouping('U', left='U', right='U')
grouping('Uacute', left='U', right='U')
grouping('Ubreve', left='U', right='U')
grouping('Ucaron', left='U', right='U')
grouping('Ucircumflex', left='U', right='U')
grouping('Udieresis', left='U', right='U')
grouping('Udieresisacute', left='U', right='U')
grouping('Udieresiscaron', left='U', right='U')
grouping('Udieresisgrave', left='U', right='U')
grouping('Udieresismacron', left='U', right='U')
grouping('Udotbelow', left='U', right='U')
grouping('Ugrave', left='U', right='U')
grouping('Uhookabove', left='U', right='U')
grouping('Uhorn', left='U', right='Uhorn')
grouping('Uhornacute', left='U', right='Uhorn')
grouping('Uhorndotbelow', left='U', right='Uhorn')
grouping('Uhorngrave', left='U', right='Uhorn')
grouping('Uhornhookabove', left='U', right='Uhorn')
grouping('Uhorntilde', left='U', right='Uhorn')
grouping('Uhungarumlaut', left='U', right='U')
grouping('Umacron', left='U', right='U')
grouping('Uogonek', left='U', right='U')
grouping('Uring', left='U', right='U')
grouping('Utilde', left='U', right='U')
grouping('V', left='V', right='V')
grouping('W', left='V', right='V')
grouping('Wacute', left='W', right='W')
grouping('Wcircumflex', left='W', right='W')
grouping('Wdieresis', left='W', right='W')
grouping('Wgrave', left='W', right='W')
grouping('X', left='X', right='K')
grouping('Y', left='V', right='V')
grouping('Yacute', left='Y', right='Y')
grouping('Ycircumflex', left='Y', right='Y')
grouping('Ydieresis', left='Y', right='Y')
grouping('Ydotbelow', left='Y', right='Y')
grouping('Ygrave', left='Y', right='Y')
grouping('Yhookabove', left='Y', right='Y')
grouping('Ytilde', left='Y', right='Y')
grouping('Z', left='Z', right='Z')
grouping('Zacute', left='Z', right='Z')
grouping('Zcaron', left='Z', right='Z')
grouping('Zdotaccent', left='Z', right='Z')
grouping('Zstroke', left='Z', right='Z')

grouping('a', left='a', right='a', italic_left='o', italic_right='u')
grouping('aacute', left='a', width='a')
grouping('abreve', left='a', width='a')
grouping('adotbelow', left='a', width='a')
grouping('abreveacute', left='a', width='a')
grouping('abrevedotbelow', left='a', width='a')
grouping('abrevegrave', left='a', width='a')
grouping('abrevehookabove', left='a', width='a')
grouping('abrevetilde', left='a', width='a')
grouping('acaron', left='a', width='a')
grouping('acircumflex', left='a', width='a')
grouping('acircumflexacute', left='a', width='a')
grouping('acircumflexdotbelow', left='a', width='a')
grouping('acircumflexgrave', left='a', width='a')
grouping('acircumflexhookabove', left='a', width='a')
grouping('acircumflextilde', left='a', width='a')
grouping('adieresis', left='a', width='a')
grouping('ae', left='a', right='e', italic_left='o')
grouping('aeacute', left='ae', width='ae', italic_left='o')
grouping('agrave', left='a', width='a')
grouping('ahookabove', left='a', width='a')
grouping('amacron', left='a', width='a')
grouping('aogonek', left='a', width='a')
grouping('aring', left='a', width='a')
grouping('aringacute', left='a', width='a')
grouping('atilde', left='a', width='a')
grouping('b', left='b', right='o')
grouping('c', left='o', right='c')
grouping('cacute', left='c', width='c')
grouping('ccaron', left='c', width='c')
grouping('ccedilla', left='c', width='c')
grouping('ccircumflex', left='c', width='c')
grouping('cdotaccent', left='c', width='c')
grouping('d', left='d', right='d')
grouping('dcaron', left='d', width='d')
grouping('dcroat', left='d', right='d')
grouping('idotless', left='i', width='i')
grouping('jdotless', left='j', width='j')
grouping('e', left='o', right='e')
grouping('eacute', left='e', width='e')
grouping('ebreve', left='e', width='e')
grouping('ecaron', left='e', width='e')
grouping('ecircumflex', left='e', width='e')
grouping('ecircumflexacute', left='e', width='e')
grouping('ecircumflexdotbelow', left='e', width='e')
grouping('ecircumflexgrave', left='e', width='e')
grouping('ecircumflexhookabove', left='e', width='e')
grouping('ecircumflextilde', left='e', width='e')
grouping('edieresis', left='e', width='e')
grouping('edotaccent', left='e', width='e')
grouping('edotbelow', left='e', width='e')
grouping('egrave', left='e', width='e')
grouping('ehookabove', left='e', width='e')
grouping('emacron', left='e', width='e')
grouping('eng', left='n', right='j')
grouping('eogonek', left='e', right='e')
grouping('eth', left='eth', right='eth')
grouping('etilde', left='e', right='e')
grouping('f', left='f', right='f')
grouping('g', left='g', right='g')
grouping('gbreve', left='g', right='g')
grouping('gcircumflex', left='g', right='g')
grouping('gcommaaccent', left='g', right='g')
grouping('gdotaccent', left='g', right='g')
grouping('germandbls', left='f', right='germandbls')
grouping('h', left='h', right='n')
grouping('hbar', width='h', right='h')
grouping('hcircumflex', width='h', right='h')
grouping('i', left='i', right='i')
grouping('iacute', left='i', right='i')
grouping('ibreve', left='idieresis', right='i')
grouping('icaron', left='idieresis', right='i')
grouping('icircumflex', left='idieresis', right='i')
grouping('idieresis', left='idieresis', right='i')
grouping('idotaccent', left='i', right='i')
grouping('idotbelow', left='i', width='i')
grouping('igrave', left='idieresis', right='i')
grouping('ihookabove', left='i', width='i')
grouping('ij', left='i', right='j')
grouping('imacron', left='idieresis', right='i')
grouping('iogonek', width='i')
grouping('itilde', left='idieresis', right='i')
grouping('j', left='j', right='j')
grouping('jcircumflex', left='jcircumflex', right='j')
grouping('k', left='h', right='k')
grouping('kcommaaccent', left='k', right='k')
grouping('kgreenlandic', left='n', right='k')
grouping('l', left='h', right='d')
grouping('lacute', left='l', right='l')
grouping('lcaron', left='l', right='dcaron')
grouping('lcommaaccent', left='l', right='l')
grouping('ldot', left='l', right='ldot')
grouping('longs', left='f', right='f')
grouping('lslash', left='lslash', right='lslash')
grouping('m', left='n', right='n')
grouping('n', left='n', right='n')
grouping('nacute', left='n', right='n')
grouping('napostrophe', left=None, right='n')
grouping('ncaron', left='n', right='n')
grouping('ncommaaccent', left='n', right='n')
grouping('ntilde', left='n', right='n')
grouping('o', left='o', right='o')
grouping('oacute', left='o', width='o')
grouping('obreve', left='o', width='o')
grouping('ocaron', left='o', width='o')
grouping('ocircumflex', left='o', width='o')
grouping('ocircumflexacute', left='o', width='o')
grouping('ocircumflexdotbelow', left='o', width='o')
grouping('ocircumflexgrave', right='o', width='o')
grouping('ocircumflexhookabove', left='o', width='o')
grouping('ocircumflextilde', left='o', width='o')
grouping('odieresis', left='o', width='o')
grouping('odotbelow', left='o', width='o')
grouping('oe', left='o', right='e')
grouping('ograve', left='o', width='o')
grouping('ohookabove', left='o', width='o')
grouping('ohorn', left='o', width='ohorn')
grouping('ohornacute', left='o', width='ohorn')
grouping('ohorndotbelow', left='o', width='ohorn')
grouping('ohorngrave', left='o', width='ohorn')
grouping('ohornhookabove', left='o', width='ohorn')
grouping('ohorntilde', left='o', width='ohorn')
grouping('ohungarumlaut', left='o', width='o')
grouping('omacron', left='o', width='o')
grouping('oslash', left='o', right='o')
grouping('oslashacute', left='oslash', right='oslash')
grouping('otilde', left='o', right='o')
grouping('p', left='p', right='o')
grouping('q', left='o', right='q')
grouping('r', left='n', right='r')
grouping('racute', left='r', right='r')
grouping('rcaron', left='r', right='r')
grouping('rcommaaccent', left='r', right='r')
grouping('s', left='s', right='s')
grouping('sacute', left='s', right='s')
grouping('scaron', left='scaron', right='s')
grouping('scedilla', left='s', right='s')
grouping('schwa', left='o', right='o')
grouping('scircumflex', left='s', right='s')
grouping('scommaaccent', left='s', right='s')
grouping('t', left='t', right='t')
grouping('tbar', left='t', right='t')
grouping('tcaron', left='t', right='t')
grouping('tcedilla', left='t', right='t')
grouping('tcommaaccent', left='t', right='t')
grouping('thorn', left='b', right='o')
grouping('u', left='u', right='u')
grouping('uacute', left='u', right='u')
grouping('ubreve', left='u', right='u')
grouping('ucaron', left='u', right='u')
grouping('ucircumflex', left='u', right='u')
grouping('udieresis', left='u', right='u')
grouping('udieresisacute', left='u', right='u')
grouping('udieresiscaron', left='u', right='u')
grouping('udieresisgrave', left='u', right='u')
grouping('udieresismacron', left='u', right='u')
grouping('udotbelow', left='u', right='u')
grouping('ugrave', left='u', right='u')
grouping('uhookabove', left='u', right='u')
grouping('uhorn', left='u', right='ohorn')
grouping('uhornacute', left='u', right='uhorn')
grouping('uhorndotbelow', left='u', right='uhorn')
grouping('uhorngrave', left='u', right='uhorn')
grouping('uhornhookabove', left='u', right='uhorn')
grouping('uhorntilde', left='u', right='uhorn')
grouping('uhungarumlaut', left='u', right='u')
grouping('umacron', left='u', right='u')
grouping('uogonek', left='u', right='u')
grouping('uring', left='u', right='u')
grouping('utilde', left='u', right='u')
grouping('v', left='v', right='v')
grouping('vrighthook', left='v', right='r')
grouping('w', left='v', right='v')
grouping('wacute', left='w', right='w')
grouping('wcircumflex', left='w', right='w')
grouping('wdieresis', left='w', right='w')
grouping('wgrave', left='w', right='w')
grouping('x', left='x', right='x')
grouping('y', left='v', right='v', italic_left='y', italic_right='y')
grouping('ydotbelow', left='y', width='y')
grouping('yacute', left='y', right='y', italic_left='y', italic_right='y')
# grouping('ydieresis', left='ydieresis', right='v', italic_left='ydieresis', italic_right='y')
# grouping('ycircumflex', left='ydieresis', right='v', italic_left='ydieresis', italic_right='y')
# grouping('ygrave', left='ydieresis', right='v', italic_left='ydieresis', italic_right='y')
# grouping('yhookabove', left='ydieresis', right='v', italic_left='ydieresis', italic_right='y')
# grouping('ytilde', left='ydieresis', right='v', italic_left='ydieresis', italic_right='y')
grouping('ydieresis', left='y', right='y', italic_left='y', italic_right='y')
grouping('ycircumflex', left='y', right='y', italic_left='y', italic_right='y')
grouping('ygrave', left='y', right='y', italic_left='y', italic_right='y')
grouping('yhookabove', left='y', right='y', italic_left='y', italic_right='y')
grouping('ytilde', left='y', right='y', italic_left='y', italic_right='y')
grouping('z', left='z', right='z')
grouping('xdotaccent', left='x', right='x')
grouping('zacute', left='z', right='z')
grouping('zcaron', left='z', right='z')
grouping('zdotaccent', left='z', right='z')
grouping('zstroke', left='z', right='z')
grouping('minusmod', left='plus', right='plus')
grouping('plusmod', left='plus', right='plus')
grouping('uptackmod', left='plus', right='plus')
grouping('uptackmod', left='plus', right='plus')
grouping('dzaltone', left='d', right='z')
grouping('dzcurl', left='d', right='zcurl')
grouping('ts', left='t', right='s')
grouping('tccurl', left='t', right='ccurl')
grouping('dblarchinvertedbelowcomb', left='seagullbelowcomb', right='seagullbelowcomb')
grouping('macronacutecomb', left='=50', right='=50')
grouping('gravemacroncomb', left='=50', right='=50')
grouping('macrongravecomb', left='=50', right='=50')
grouping('acutemacroncomb', left='=50', right='=50')
grouping('graveacutegravecomb', left='=50', right='=50')
grouping('acutegraveacutecomb', left='=50', right='=50')
grouping('closeup', left='undertie', right='undertie')
grouping('Usmall', left='u', right='=|u')
grouping('Dsmall', left='n', right='o')
grouping('hv', left='h', right='vhook')
grouping('lambdastroke', left='lambda', right='lambda')
grouping('lbar', left='lslash', right='lslash')
grouping('brevebelowcomb', left='brevecomb', right='brevecomb')
grouping('macronbelowcomb', left='macroncomb', right='macroncomb')
grouping('chook', left='c', right='dhook')
grouping('dhook', left='d')
grouping('dhookandtail', left='d', right='dhook')
grouping('esh', right='dhook')
grouping('ghook', left='g', right='dhook')
grouping('Gsmallhook', left='Gsmall', right='dhook')
grouping('tesh', left='t', right='esh')


grouping('quotedblleft', left='=|quoteright', right='=|quoteright')
grouping('quoteleft', left='=|quoteright', right='=|quoteright')
grouping('quotedblright', left='quoteright', right='quoteright')
grouping('quoteright', left='quoteright', right='quoteright')
grouping('quotedblbase', left='quoteright', right='quoteright')
grouping('quotesinglbase', left='quoteright', right='quoteright')
grouping('quotereversed', left='=|quoteright', right='=|quoteright')
grouping('period', left='period', right='period')
grouping('colon', left='period', right='period')
grouping('bullet', left='period', right='period')
grouping('periodcentered', left='period', right='period')
grouping('comma', left='period', right='period')
grouping('semicolon', left='comma', right='comma')
grouping('exclam', left='period', right='period')
grouping('questiondown', left='question', right='question')
grouping('ellipsis', left='period', right='period')
grouping('daggerdbl', left='dagger', right='dagger')
grouping('product', left='H', right='H')
grouping('cent', left='c', right='c')
grouping('dollar', left='S', right='S')
grouping('micro', left='p', right='u')
grouping('guillemetright', left='=|guilsinglleft', right='=|guilsinglleft')
grouping('guilsinglright', left='=|guilsinglleft', right='=|guilsinglleft')
grouping('guillemetleft', left='guilsinglleft', right='guilsinglleft')
grouping('minus', left='plus', right='plus')
grouping('equal', left='plus', right='plus')
grouping('notequal', left='equal', right='equal')
grouping('divide', left='plus', right='plus')
grouping('plusminus', left='plus', right='plus')
grouping('bar', left='plus', right='plus')
grouping('brokenbar', left='plus', right='plus')
grouping('asciitilde', left='plus', right='plus')
grouping('approxequal', left='plus', right='plus')
grouping('softhyphen', left='hyphen', right='hyphen')
grouping('hyphentwo', left='hyphen', right='hyphen')
grouping('horizontalbar', left='hyphen', right='hyphen')
grouping('nonbreakinghyphen', left='hyphen', right='hyphen')
grouping('bulletoperator', left='period', right='period')
grouping('divisionslash', left='slash', right='slash')
grouping('parenright', left='=|parenleft', right='=|parenleft')
grouping('bracketright', left='=|bracketleft', right='=|bracketleft')
grouping('braceright', left='=|braceleft', right='=|braceleft')
grouping('parenright.sups', left='=|parenleft.sups', right='=|parenleft.sups')
grouping('parenright.dnom', left='=|parenleft.dnom', right='=|parenleft.dnom')
grouping('parenright.numr', left='=|parenleft.numr', right='=|parenleft.numr')
grouping('parenright.tf', left='=|parenleft.tf', right='=|parenleft.tf')
grouping('parenright-ar', left='=|parenleft-ar', right='=|parenleft-ar')
grouping('less', left='=|greater', right='=|greater')
grouping('lessequal', left='=|greater', right='=|greater')
grouping('greaterequal', left='=greater', right='=greater')
grouping('firsttonechinese', left='=50', right='=50')
grouping('apostrophemod', left='quoteright', right='quoteright')
grouping('commaabovecomb', left='commaaccentcomb', right='commaaccentcomb')
grouping('underscoredbl', left='underscore', right='underscore')
grouping('overline', left='underscore', right='underscore')
grouping('second', left='minute', right='minute')
grouping('lowernumeral-greek', left='numeral-greek', right='numeral-greek')
grouping('published', left='copyright', right='copyright')
grouping('exclamdouble', left='exclam', right='exclam')
grouping('dblgravecomb', left='=|hungarumlautcomb', right='=|hungarumlautcomb')
grouping('caroncomb.alt', right='=50')
grouping('onehalf', left='one.numr', right='two.dnom')
grouping('onequarter', left='one.numr', right='four.dnom')
grouping('threequarters', left='three.numr', right='four.dnom')
grouping('oneeighth', left='one.numr', right='eight.dnom')
grouping('threeeighths', left='three.numr', right='eight.dnom')
grouping('fiveeighths', left='five.numr', right='eight.dnom')
grouping('seveneighths', left='seven.numr', right='eight.dnom')

grouping('n.subs', left='n.sups', right='n.sups')

grouping('plus.subs', left='plus.sups', right='plus.sups')
grouping('minus.subs', left='minus.sups', right='minus.sups')
grouping('equal.subs', left='equal.sups', right='equal.sups')
grouping('parenleft.subs', left='parenleft.sups', right='parenleft.sups')
grouping('parenright.subs', left='parenright.sups', right='parenright.sups')

grouping('plus.sups', left='equal.subs', right='equal.subs')
grouping('minus.sups', left='equal.subs', right='equal.subs')
grouping('equal.sups', left='equal.subs', right='equal.subs')
grouping('kip', left='Eth', right='K')
grouping('cedi', left='C', right='C')
grouping('colonsign', left='C', right='C')
grouping('guarani', left='G', right='G')
grouping('rupee', left='R', right='s')
grouping('tenge', left='T', right='T')
grouping('tugrik', left='T', right='T')
grouping('bitcoin', left='B', right='B')

grouping('zeroWidthNoBreakSpace', left='=0', width='=0')
grouping('NULL', left=0, right=0, width=0)
grouping('CR', left=0, right=0, width='space')
grouping('nbspace', left=0, right=0, width='space')
grouping('enspace', left=0, right=0, width='=emspace*0.5')
grouping('punctuationspace', left=0, right=0, width='period')
grouping('thinspace', left=0, right=0, width='=space*0.6')
grouping('hairspace', left=0, right=0, width='=space*0.3')
grouping('zerowidthspace', left=0, right=0, width='=0')


# Cyrillic
grouping('A-cy', left='A-cy', right='A-cy')
grouping('Abreve-cy', left='A-cy', right='A-cy')
grouping('Adieresis-cy', left='A-cy', right='A-cy')
grouping('Aie-cy', left='Aie-cy', right='Ie-cy')
grouping('Be-cy', left='En-cy', right='Be-cy')
grouping('Che-cy', left='Che-cy', right='En-cy')
grouping('Cheabkhasian-cy', left='Cheabkhasian-cy', right='Cheabkhasian-cy')
grouping('Chedescender-cy', left='Che-cy', right='Tse-cy')
grouping('Chedescenderabkhasian-cy', left='Cheabkhasian-cy', right='Cheabkhasian-cy')
grouping('Chedieresis-cy', left='Che-cy', right='En-cy')
grouping('Chekhakassian-cy', left='Che-cy', right='En-cy')
grouping('Cheverticalstroke-cy', left='Che-cy', right='En-cy')
grouping('De-cy', left='De-cy', right='Tse-cy')
grouping('Dje-cy', left='Te-cy', right='Be-cy')
grouping('Dze-cy', left='Dze-cy', right='Dze-cy')
grouping('Dzeabkhasian-cy', left='Ze-cy', right='Dzeabkhasian-cy')
grouping('Dzhe-cy', left='En-cy', right='En-cy')
grouping('E-cy', left='O-cy', right='Es-cy')
grouping('Edieresis-cy', left='Ze-cy', right='O-cy')
grouping('Ef-cy', left='Ef-cy', right='Ef-cy')
grouping('El-cy', left='El-cy', right='El-cy')
grouping('Elhook-cy', left='El-cy', right='El-cy')
grouping('Eltail-cy', left='El-cy')
grouping('Em-cy', left='En-cy', right='En-cy')
grouping('Emtail-cy', left='Em-cy', right='Eltail-cy')
grouping('En-cy', left='En-cy', right='En-cy')
grouping('Endescender-cy', left='En-cy', right='Tse-cy')
grouping('Enghe-cy', left='En-cy', right='Ge-cy')
grouping('Enhook-cy', left='En-cy', right='En-cy')
grouping('Entail-cy', left='En-cy', right='Eltail-cy')
grouping('Er-cy', left='En-cy', right='Er-cy')
grouping('Ereversed-cy', left='Ze-cy', right='O-cy')
grouping('Ertick-cy', left='En-cy', right='Er-cy')
grouping('Es-cy', left='O-cy', right='Es-cy')
grouping('Esdescender-cy', left='Es-cy', right='Es-cy')
grouping('Fita-cy', left='O-cy', right='O-cy')
grouping('Ge-cy', left='En-cy', right='Ge-cy')
grouping('Ghedescender-cy', left='En-cy', right='Ge-cy')
grouping('Ghemiddlehook-cy', left='En-cy', right='Be-cy')
grouping('Ghestroke-cy', right='Ge-cy')
grouping('Gheupturn-cy', left='En-cy', right='Ge-cy')
grouping('Gje-cy', left='En-cy', right='Ge-cy')
grouping('Ha-cy', left='Ha-cy', right='Ha-cy')
grouping('Haabkhasian-cy', left='O-cy', right='Haabkhasian-cy')
grouping('Hadescender-cy', left='Ha-cy', right='Ha-cy')
grouping('Hahook-cy', left='Ha-cy', right='Ha-cy')
grouping('Hardsign-cy', left='Te-cy', right='Softsign-cy')
grouping('I-cy', left='En-cy', right='En-cy')
grouping('Ia-cy', left='Ia-cy', right='En-cy')
grouping('Idieresis-cy', left='En-cy', right='En-cy')
grouping('Ie-cy', left='En-cy', right='Ie-cy')
grouping('Iebreve-cy', left='En-cy', right='Ie-cy')
grouping('Iegrave-cy', left='En-cy', right='Ie-cy')
grouping('Ii-cy', left='En-cy', right='En-cy')
grouping('Iigrave-cy', left='Ii-cy', right='Ii-cy')
grouping('Iishort-cy', left='Ii-cy', right='Ii-cy')
grouping('Imacron-cy', left='Ii-cy', right='Ii-cy')
grouping('Io-cy', left='En-cy', right='Ie-cy')
grouping('Ishorttail-cy', left='En-cy', right='De-cy')
grouping('Iu-cy', left='En-cy', right='O-cy')
grouping('Izhitsa-cy', left='Izhitsa-cy', right='Izhitsa-cy')
grouping('Je-cy', left='Je-cy', right='Je-cy')
grouping('Ka-cy', left='En-cy', right='Zhe-cy')
grouping('Kabashkir-cy', left='Te-cy', right='Zhe-cy')
grouping('Kadescender-cy', left='En-cy', right='')
grouping('Kahook-cy', left='En-cy', right='Be-cy')
grouping('Kastroke-cy', left='Yat-cy', right='Zhe-cy')
grouping('Kaverticalstroke-cy', left='En-cy', right='Zhe-cy')
grouping('Kje-cy', left='En-cy', right='Zhe-cy')
grouping('Lje-cy', left='El-cy', right='Softsign-cy')
grouping('Nje-cy', left='En-cy', right='Softsign-cy')
grouping('O-cy', left='O-cy', right='O-cy')
grouping('Obarred-cy', left='O-cy', right='O-cy')
grouping('Obarreddieresis-cy', left='O-cy', right='O-cy')
grouping('Odieresis-cy', left='O-cy', right='O-cy')
grouping('Palochka-cy', left='En-cy', right='En-cy')
grouping('Pe-cy', left='En-cy', right='En-cy')
grouping('Pemiddlehook-cy', left='En-cy', right='Be-cy')
grouping('Schwa-cy', left='Schwa-cy', right='O-cy')
grouping('Schwadieresis-cy', left='Schwa-cy', right='O-cy')
grouping('Semisoftsign-cy', left='Ghestroke-cy', right='Softsign-cy')
grouping('Sha-cy', left='En-cy', right='En-cy')
grouping('Shcha-cy', left='En-cy', right='Tse-cy')
grouping('Shha-cy', left='En-cy', right='Shha-cy')
grouping('Softsign-cy', left='En-cy', right='Softsign-cy')
grouping('Te-cy', left='Te-cy', right='Ge-cy')
grouping('Tedescender-cy', left='Te-cy', right='Ge-cy')
grouping('Tetse-cy', left='Te-cy', right='De-cy')
grouping('Tse-cy', left='En-cy', right='')
grouping('Tshe-cy', left='Te-cy', right='Shha-cy')
grouping('U-cy', left='U-cy', right='U-cy')
grouping('Udieresis-cy', left='U-cy', right='U-cy')
grouping('Uhungarumlaut-cy', left='U-cy', right='U-cy')
grouping('Umacron-cy', left='U-cy', right='U-cy')
grouping('Ushort-cy', left='U-cy', right='U-cy')
grouping('Ustraight-cy', left='Ustraight-cy', right='Ustraight-cy')
grouping('Ustraightstroke-cy', left='Ustraight-cy', right='Ustraight-cy')
grouping('Ve-cy', left='En-cy', right='Ve-cy')
grouping('Yat-cy', left='Yat-cy', right='Softsign-cy')
grouping('Yeru-cy', left='En-cy', right='En-cy')
grouping('Yerudieresis-cy', left='En-cy', right='En-cy')
grouping('Yi-cy', left='En-cy', right='En-cy')
grouping('Ze-cy', left='Ze-cy', right='Ve-cy')
grouping('Zedescender-cy', left='Ze-cy', right='Ze-cy')
grouping('Zedieresis-cy', left='Ze-cy', right='Ze-cy')
grouping('Zhe-cy', left='Zhe-cy', right='Zhe-cy')
grouping('Zhebreve-cy', left='Zhe-cy', right='Zhe-cy')
grouping('Zhedescender-cy', left='Zhe-cy', right='Kadescender-cy')
grouping('Zhedieresis-cy', left='Zhe-cy', right='Zhe-cy')
grouping('Reversedze-cy', left='=|Ve-cy', right='Es-cy')
grouping('Ef-cy.loclBGR', left='O-cy', right='O-cy')
grouping('softsign-cy.loclBGR', left='u', right='softsign-cy')
grouping('hardsign-cy.loclBGR', left='te-cy', right='softsign-cy', italic_left='hardsign-cy')
grouping('ka-cy.loclBGR', left='h', right='Ka-cy')
grouping('Iishorttail-cy', left='En-cy', right='Eltail-cy')
grouping('iishorttail-cy', left='En-cy', right='eltail-cy')
grouping('Uk-cy', left='O-cy', right='u-cy')
grouping('uni047A', left='O-cy', right='O-cy')
grouping('uni047B', left='o-cy', right='o-cy')
grouping('uni047C', left='O-cy', right='O-cy')
grouping('uni047D', left='o-cy', right='o-cy')
grouping('Ksi-cy', left='Ze-cy', right='Ze-cy')
grouping('ksi-cy', left='ze-cy', right='ze-cy')

grouping('tsebase-cy', left='en-cy', right='en-cy', italic_left='ii-cy', italic_right='')
grouping('a-cy', left='a-cy', right='a-cy', italic_left='o-cy', italic_right='en-cy')
grouping('abreve-cy', left='a-cy', right='a-cy')
grouping('adieresis-cy', left='a-cy', right='a-cy')
grouping('aie-cy', left='a-cy', right='ie-cy')
grouping('be-cy', left='be-cy', right='be-cy')
grouping('be-cy.loclSRB', left='be-cy', right='be-cy', italic_left='de-cy', italic_right='be-cy')
grouping('che-cy', left='che-cy', right='en-cy', italic_right='en-cy')
grouping('cheabkhasian-cy', left='cheabkhasian-cy', right='ie-cy')
grouping('chedescender-cy', left='che-cy', right='tse-cy')
grouping('chedescenderabkhasian-cy', left='cheabkhasian-cy', right='ie-cy')
grouping('chedieresis-cy', left='che-cy', right='en-cy')
grouping('chekhakassian-cy', left='che-cy', right='en-cy')
grouping('cheverticalstroke-cy', left='che-cy', right='en-cy', italic_right='en-cy')
grouping('de-cy', left='', right='tse-cy')
grouping('de-cy.loclSRB', left='de-cy.loclSRB', right='de-cy.loclSRB', italic_left='o-cy', italic_right='de-cy.loclSRB')
grouping('dje-cy', left='dje-cy', right='dje-cy')
grouping('dze-cy', left='dze-cy', right='dze-cy')
grouping('dzeabkhasian-cy', left='dzeabkhasian-cy', right='dzeabkhasian-cy')
grouping('dzhe-cy', left='en-cy', right='en-cy', italic_left='sha-cy', italic_right='en-cy')
grouping('e-cy', left='o-cy', right='es-cy')
grouping('edieresis-cy', left='ereversed-cy', right='o-cy')
grouping('ef-cy', left='o-cy', right='o-cy')
grouping('el-cy', left='el-cy', right='en-cy', italic_right='el-cy')
grouping('eltail-cy', left='el-cy')
grouping('em-cy', left='en-cy', right='en-cy', italic_right='en-cy')
grouping('emtail-cy', left='em-cy', right='eltail-cy', italic_right='eltail-cy')
grouping('en-cy', left='en-cy', right='en-cy', italic_right='en-cy')
grouping('endescender-cy', left='en-cy', right='tse-cy', italic_right='tse-cy')
grouping('enghe-cy', left='en-cy', right='ge-cy', italic_right='gheupturn-cy')
grouping('enhook-cy', left='en-cy', right='en-cy', italic_right='je-cy')
grouping('entail-cy', left='en-cy', right='eltail-cy')
grouping('er-cy', left='er-cy', right='o-cy')
grouping('ereversed-cy', left='ereversed-cy', right='o-cy')
grouping('ertick-cy', left='er-cy', right='o-cy')
grouping('es-cy', left='o-cy', right='es-cy')
grouping('esdescender-cy', left='es-cy', right='es-cy')
grouping('fita-cy', left='o-cy', right='o-cy')
grouping('ge-cy', left='en-cy', right='ge-cy', italic_left='ge-cy')
grouping('ge-cy.loclSRB', left='i-cy', right='i-cy', italic_right='i-cy')
grouping('gedescender-cy', left='en-cy', right='ge-cy', italic_left='ge-cy', italic_right='ge-cy')
grouping('ghemiddlehook-cy', left='en-cy', right='ghemiddlehook-cy')
grouping('ghestroke-cy', left='', right='ge-cy', italic_left='ge-cy', italic_right='ge-cy')
grouping('gheupturn-cy', left='en-cy', right='ge-cy', italic_right='gheupturn-cy')
grouping('gje-cy', left='en-cy', right='ge-cy', italic_left='ge-cy')
grouping('ha-cy', left='ha-cy', right='ha-cy')
grouping('haabkhasian-cy', left='o-cy', right='haabkhasian-cy')
grouping('hadescender-cy', left='ha-cy', right='ha-cy')
grouping('hardsign-cy', left='te-cy', right='softsign-cy', italic_left='hardsign-cy')
grouping('i-cy', left='i-cy', right='i-cy')
grouping('ia-cy', left='ia-cy', right='en-cy', italic_right='en-cy')
grouping('idieresis-cy', left='en-cy', right='en-cy')
grouping('ie-cy', left='o-cy', right='ie-cy')
grouping('iebreve-cy', width='ie-cy', right='ie-cy')
grouping('iegrave-cy', width='ie-cy', right='ie-cy')
grouping('ii-cy', left='en-cy', right='en-cy', italic_left='sha-cy', italic_right='en-cy')
grouping('iigrave-cy', left='ii-cy', right='ii-cy')
grouping('iishort-cy', left='ii-cy', right='ii-cy')
grouping('imacron-cy', left='ii-cy', right='ii-cy')
grouping('io-cy', left='iegrave-cy', right='ie-cy')
grouping('ishorttail-cy', left='en-cy', right='en-cy', italic_right='tse-cy')
grouping('iu-cy', left='en-cy', right='o-cy')
grouping('izhitsa-cy', left='izhitsa-cy', right='izhitsa-cy')
grouping('je-cy', left='je-cy', right='je-cy')
grouping('ka-cy', left='en-cy', right='ka-cy')
grouping('kabashkir-cy', left='te-cy', right='ka-cy', italic_left='hardsign-cy')
grouping('kadescender-cy', left='en-cy', right='')
grouping('kahook-cy', left='en-cy', right='kahook-cy')
grouping('kastroke-cy', left='tshe-cy', right='ka-cy')
grouping('kaverticalstroke-cy', left='en-cy', right='ka-cy')
grouping('kje-cy', left='en-cy', right='ka-cy')
grouping('lje-cy', left='lje-cy', right='softsign-cy')
grouping('nje-cy', left='en-cy', right='softsign-cy')
grouping('o-cy', left='o-cy', right='o-cy', italic_left='o-cy')
grouping('obarred-cy', left='o-cy', right='o-cy', italic_left='o-cy')
grouping('obarreddieresis-cy', left='o-cy', right='o-cy')
grouping('odieresis-cy', left='o-cy', right='o-cy')
grouping('pe-cy', left='en-cy', right='en-cy', italic_right='pe-cy')
grouping('pe-cy.loclSRB', left='a-cy', right='a-cy', italic_left='iishort-cy', italic_right='en-cy')
grouping('pemiddlehook-cy', left='en-cy', right='ghemiddlehook-cy')
grouping('palochka-cy', left='palochka-cy', right='palochka-cy')
grouping('schwa-cy', left='schwa-cy', right='o-cy')
grouping('schwadieresis-cy', left='schwa-cy', right='o-cy')
grouping('semisoftsign-cy', left='f', right='softsign-cy')
grouping('sha-cy', left='en-cy', right='en-cy', italic_left='sha-cy', italic_right='en-cy')
grouping('shcha-cy', left='en-cy', right='tse-cy', italic_left='sha-cy', italic_right='tse-cy')
grouping('shha-cy', left='tshe-cy', right='tshe-cy', italic_left='dje-cy', italic_right='pe-cy')
grouping('softsign-cy', left='en-cy', right='softsign-cy')
grouping('te-cy', left='te-cy', right='ge-cy', italic_left='te-cy', italic_right='ge-cy')
grouping('te-cy.loclSRB', left='a-cy', right='a-cy', italic_left='sha-cy', italic_right='en-cy')
grouping('tedescender-cy', left='te-cy', right='ge-cy', italic_left='en-cy', italic_right='tse-cy')
grouping('tetse-cy', left='te-cy', right='tse-cy', italic_left='tetse-cy', italic_right='tse-cy')
grouping('tse-cy', left='en-cy', right='', italic_left='sha-cy', italic_right='tse-cy')
grouping('tshe-cy', left='tshe-cy', right='tshe-cy', italic_left='dje-cy', italic_right='pe-cy')
grouping('u-cy', left='u-cy', right='u-cy')
grouping('udieresis-cy', left='u-cy', right='u-cy')
grouping('uhungarumlaut-cy', left='u-cy', right='u-cy')
grouping('umacron-cy', left='u-cy', right='u-cy')
grouping('ushort-cy', left='u-cy', right='u-cy')
grouping('ustraight-cy', left='u-cy', right='u-cy')
grouping('ustraightstroke-cy', left='ustraight-cy', right='ustraight-cy')
grouping('ve-cy', left='en-cy', right='ve-cy', italic_left='o-cy')
grouping('yat-cy', left='yat-cy', right='softsign-cy', italic_left='en-cy')
grouping('yeru-cy', left='en-cy', right='en-cy', italic_right='en-cy')
grouping('yerudieresis-cy', left='en-cy', right='en-cy')
grouping('yi-cy', left='i-cy', right='i-cy')
grouping('ze-cy', left='ze-cy', right='ve-cy')
grouping('zedescender-cy', left='ze-cy', right='ze-cy')
grouping('zedieresis-cy', left='ze-cy', right='ze-cy')
grouping('zhe-cy', left='zhe-cy', right='ka-cy', italic_right='zhe-cy')
grouping('zhe-cy.loclBGR', left='zhe-cy', right='zhe-cy')
grouping('zhebreve-cy', left='zhe-cy', right='ka-cy')
grouping('zhedescender-cy', left='zhe-cy', right='kadescender-cy', italic_right='kadescender-cy')
grouping('zhedieresis-cy', left='zhe-cy', right='ka-cy')
grouping('hahook-cy', left='ha-cy', right='ha-cy')
grouping('reversedze-cy', left='=|ve-cy', right='es-cy')
grouping('elhook-cy', left='el-cy', right='dje-cy')
grouping('we-cy', left='u-cy', right='u-cy')
grouping('Pedescender-cy', left='En-cy', right='Tse-cy')
grouping('pedescender-cy', left='en-cy', right='tse-cy')
grouping('shhadescender-cy', left='shha-cy', right='tse-cy')
grouping('Izhitsa-cy', left='Ustraight-cy')
grouping('izhitsa-cy', left='v')
grouping('Shhadescender-cy', left='En-cy', right='Tse-cy')
grouping('shcha-cy.loclBGR', left='ii-cy.loclBGR', right='tse-cy')
grouping('tse-cy.loclBGR', left='u', right='tse-cy')
grouping('iu-cy.loclBGR', left='l', right='o-cy')
grouping('De-cy.loclBGR', left='De-cy', right='De-cy')
grouping('sha-cy.loclBGR', left='u', right='u')
grouping('Eiotified-cy', left='H', right='E-cy')
grouping('Yuslittle-cy', left='A', right='A')
grouping('Yuslittleiotified-cy', left='H', right='A')
grouping('Yusbig-cy', left='=|Shha-cy', right='Shha-cy')
grouping('Yusbigiotified-cy', left='H', right='Yusbig-cy')
grouping('psi-cy', left='u', right='=|u')
grouping('Omega-cy', left='U', right='=|U')
grouping('omega-cy', left='u', right='=|u')
grouping('eiotified-cy', left='n', right='e-cy')
grouping('yuslittle-cy', left='v', right='v')
grouping('yuslittleiotified-cy', left='h', right='a')
grouping('yusbig-cy', left='=|shha-cy', right='shha-cy')
grouping('yusbigiotified-cy', left='h', right='yusbig-cy')


grouping('Alpha', left='Alpha', right='Alpha')
grouping('Alphatonos', left='Omegadasiavaria', right='Alpha')
grouping('Beta', left='Beta', right='Beta')
grouping('Chi', left='=|Kappa', right='Kappa')
grouping('Delta', left='Alpha', right='Alpha')
grouping('Epsilon', left='Beta', right='Epsilon')
grouping('Epsilontonos', left='Omegadasiavaria', right='Epsilon')
grouping('Eta', left='Beta', right='Eta')
grouping('Etatonos', left='Omegadasiavaria', right='Eta')
grouping('Gamma', left='Beta', right='Gamma')
grouping('Iota', left='Beta', right='Eta')
grouping('Iotadieresis', left='Beta', right='Eta')
grouping('Iotatonos', left='Omegadasiavaria', right='Eta')
grouping('Kappa', left='Beta', right='Kappa')
grouping('Lambda', left='Alpha', right='Alpha')
grouping('Mu', left='Beta', right='Eta')
grouping('Nu', left='Beta', right='Nu')
grouping('Omega', left='Omega', right='Omega')
grouping('Omegatonos', left='Omegadasiavaria', right='Omega')
grouping('Omicron', left='Omicron', right='Omicron')
grouping('Omicrontonos', left='Omegadasiavaria', right='Omicron')
grouping('Phi', left='Phi', right='Phi')
grouping('Pi', left='Beta', right='Eta')
grouping('Psi', left='Psi', right='Psi')
grouping('Rho', left='Beta', right='Rho')
grouping('Sigma', left='Sigma', right='Epsilon')
grouping('Tau', left='Tau', right='Gamma')
grouping('Theta', left='Omicron', right='Omicron')
grouping('Upsilon', left='Upsilon', right='Upsilon')
grouping('Upsilondieresis', left='Upsilon', right='Upsilon')
grouping('Upsilontonos', left='Omegadasiavaria', right='Upsilon')
grouping('Xi', left='Xi', right='Epsilon')
grouping('Zeta', left='Zeta', right='Zeta')

grouping('alpha', left='omicron', right='alpha')
grouping('alphatonos', left='omicron', right='alpha')
grouping('beta', left='beta', right='beta')
grouping('chi', left='chi', right='chi')
grouping('delta', left='omicron', right='delta')
grouping('epsilon', left='epsilon', right='epsilon')
grouping('epsilontonos', left='epsilon', right='epsilon')
grouping('eta', left='eta', right='eta')
grouping('etatonos', left='eta', right='eta')
grouping('gamma', left='gamma', right='gamma')
grouping('iota', left='iota', right='iota')
grouping('iotatonos', left='iotatonos', right='iota')
grouping('iotadieresis', left='iotadieresis', right='iotadieresis')
grouping('iotadieresistonos', left='iotadieresistonos', right='iotadieresistonos')
grouping('kappa', left='eta', right='kappa')
grouping('lambda', left='lambda', right='lambda')
grouping('mu', left='mu', right='mu')
grouping('nu', left='gamma', right='gamma')
grouping('omega', left='omicron', right='omicron')
grouping('omegatonos', left='omicron', right='omicron')
grouping('omicron', left='omicron', right='omicron')
grouping('omicrontonos', left='omicron', right='omicron')
grouping('phi', left='omicron', right='omicron')
grouping('pi', left='pi', right='pi')
grouping('pi', left='f', right='t')
grouping('psi', left='upsilon', right='upsilon')
grouping('rho', left='rho', right='omicron')
grouping('sigma', left='omicron', right='sigma')
grouping('sigmafinal', left='omicron', right='sigmafinal')
grouping('tau', left='tau', right='tau')
grouping('theta', left='theta', right='theta')
grouping('upsilon', left='upsilon', right='upsilon')
grouping('upsilondieresis', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilondieresistonos', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilontonos', left='upsilon', right='upsilondieresistonos')
grouping('xi', left='xi', right='xi')
grouping('zeta', left='zeta', right='zeta')


grouping('Alphadasia', left='=0', right='Alpha')
grouping('Alphadasiaoxia', left='=0', right='Alpha')
grouping('Alphadasiaoxiaypogegrammeni', left='=0', right='Alpha')
grouping('Alphadasiaoxiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphadasiaperispomeni', left='=0', right='Alpha')
grouping('Alphadasiaperispomeniypogegrammeni', left='=0', right='Alpha')
grouping('Alphadasiaperispomeniypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphadasiavaria', left='=0', right='Alpha')
grouping('Alphadasiavariaypogegrammeni', left='=0', right='Alpha')
grouping('Alphadasiavariaypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphadasiaypogegrammeni', left='=0', right='Alpha')
grouping('Alphadasiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphamacron', left='Alpha', right='Alpha')
grouping('Alphaoxia', left='=0', right='Alpha')
grouping('Alphapsili', left='=0', right='Alpha')
grouping('Alphapsilioxia', left='=0', right='Alpha')
grouping('Alphapsilioxiaypogegrammeni', left='=0', right='Alpha')
grouping('Alphapsilioxiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphapsiliperispomeni', left='=0', right='Alpha')
grouping('Alphapsiliperispomeniypogegrammeni', left='=0', right='Alpha')
grouping('Alphapsiliperispomeniypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphapsilivaria', left='=0', right='Alpha')
grouping('Alphapsilivariaypogegrammeni', left='=0', right='Alpha')
grouping('Alphapsilivariaypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphapsiliypogegrammeni', left='=0', right='Alpha')
grouping('Alphapsiliypogegrammeni.ss03', left='=0', right='iota')
grouping('Alphavaria', left='=0', right='Alpha')
grouping('Alphavrachy', left='Alpha', right='Alpha')
grouping('Alphaypogegrammeni', left='Alpha', right='Alpha')
grouping('Alphaypogegrammeni.ss03', left='Alpha', right='iota')
grouping('Epsilondasia', left='=0', right='Epsilon')
grouping('Epsilondasiaoxia', left='=0', right='Epsilon')
grouping('Epsilondasiavaria', left='=0', right='Epsilon')
grouping('Epsilonoxia', left='=0', right='Epsilon')
grouping('Epsilonpsili', left='=0', right='Epsilon')
grouping('Epsilonpsilioxia', left='=0', right='Epsilon')
grouping('Epsilonpsilivaria', left='=0', right='Epsilon')
grouping('Epsilonvaria', left='=0', right='Epsilon')
grouping('Etadasia', left='=0', right='Eta')
grouping('Etadasiaoxia', left='=0', right='Eta')
grouping('Etadasiaoxiaypogegrammeni', left='=0', right='Eta')
grouping('Etadasiaoxiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Etadasiaperispomeni', left='=0', right='Eta')
grouping('Etadasiaperispomeniypogegrammeni', left='=0', right='Eta')
grouping('Etadasiaperispomeniypogegrammeni.ss03', left='=0', right='iota')
grouping('Etadasiavaria', left='=0', right='Eta')
grouping('Etadasiavariaypogegrammeni', left='=0', right='Eta')
grouping('Etadasiavariaypogegrammeni.ss03', left='=0', right='iota')
grouping('Etadasiaypogegrammeni', left='=0', right='Eta')
grouping('Etadasiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Etaoxia', left='=0', right='Eta')
grouping('Etapsili', left='=0', right='Eta')
grouping('Etapsilioxia', left='=0', right='Eta')
grouping('Etapsilioxiaypogegrammeni', left='=0', right='Eta')
grouping('Etapsilioxiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Etapsiliperispomeni', left='=0', right='Eta')
grouping('Etapsiliperispomeniypogegrammeni', left='=0', right='Eta')
grouping('Etapsiliperispomeniypogegrammeni.ss03', left='=0', right='iota')
grouping('Etapsilivaria', left='=0', right='Eta')
grouping('Etapsilivariaypogegrammeni', left='=0', right='Eta')
grouping('Etapsilivariaypogegrammeni.ss03', left='=0', right='iota')
grouping('Etapsiliypogegrammeni', left='=0', right='Eta')
grouping('Etapsiliypogegrammeni.ss03', left='=0', right='iota')
grouping('Etavaria', left='=0', right='Eta')
grouping('Etaypogegrammeni', left='Eta', right='Eta')
grouping('Etaypogegrammeni.ss03', left='Eta', right='iota')
grouping('Iotadasia', left='=0', right='Iota')
grouping('Iotadasiaoxia', left='=0', right='Iota')
grouping('Iotadasiaperispomeni', left='=0', right='Iota')
grouping('Iotadasiavaria', left='=0', right='Iota')
grouping('Iotamacron', left='Imacron', right='Imacron')
grouping('Iotaoxia', left='=0', right='Iota')
grouping('Iotapsili', left='=0', right='Iota')
grouping('Iotapsilioxia', left='=0', right='Iota')
grouping('Iotapsiliperispomeni', left='=0', right='Iota')
grouping('Iotapsilivaria', left='=0', right='Iota')
grouping('Iotavaria', left='=0', right='Iota')
grouping('Iotavrachy', left='Ibreve', right='Ibreve')
grouping('Omegadasia', left='=0', right='Omega')
grouping('Omegadasiaoxia', left='=0', right='Omega')
grouping('Omegadasiaoxiaypogegrammeni', left='=0', right='Omega')
grouping('Omegadasiaoxiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegadasiaperispomeni', left='=0', right='Omega')
grouping('Omegadasiaperispomeniypogegrammeni', left='=0', right='Omega')
grouping('Omegadasiaperispomeniypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegadasiavaria', left='=0', right='Omega')
grouping('Omegadasiavariaypogegrammeni', left='=0', right='Omega')
grouping('Omegadasiavariaypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegadasiaypogegrammeni', left='=0', right='Omega')
grouping('Omegadasiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegaoxia', left='=0', right='Omega')
grouping('Omegapsili', left='=0', right='Omega')
grouping('Omegapsilioxia', left='=0', right='Omega')
grouping('Omegapsilioxiaypogegrammeni', left='=0', right='Omega')
grouping('Omegapsilioxiaypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegapsiliperispomeni', left='=0', right='Omega')
grouping('Omegapsiliperispomeniypogegrammeni', left='=0', right='Omega')
grouping('Omegapsiliperispomeniypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegapsilivaria', left='=0', right='Omega')
grouping('Omegapsilivariaypogegrammeni', left='=0', right='Omega')
grouping('Omegapsilivariaypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegapsiliypogegrammeni', left='=0', right='Omega')
grouping('Omegapsiliypogegrammeni.ss03', left='=0', right='iota')
grouping('Omegavaria', left='=0', right='Omega')
grouping('Omegaypogegrammeni', left='Omega', right='Omega')
grouping('Omegaypogegrammeni.ss03', left='Omega', right='iota')
grouping('Omicrondasia', left='=0', right='Omicron')
grouping('Omicrondasiaoxia', left='=0', right='Omicron')
grouping('Omicrondasiavaria', left='=0', right='Omicron')
grouping('Omicronoxia', left='=0', right='Omicron')
grouping('Omicronpsili', left='=0', right='Omicron')
grouping('Omicronpsilioxia', left='=0', right='Omicron')
grouping('Omicronpsilivaria', left='=0', right='Omicron')
grouping('Omicronvaria', left='=0', right='Omicron')
grouping('Rhodasia', left='=0', right='Rho')
grouping('Upsilondasia', left='=0', right='Upsilon')
grouping('Upsilondasiaoxia', left='=0', right='Upsilon')
grouping('Upsilondasiaperispomeni', left='=0', right='Upsilon')
grouping('Upsilondasiavaria', left='=0', right='Upsilon')
grouping('Upsilonmacron', left='Upsilon', right='Upsilon')
grouping('Upsilonoxia', left='=0', right='Upsilon')
grouping('Upsilonvaria', left='=0', right='Upsilon')
grouping('Upsilonvrachy', left='Upsilon', right='Upsilon')

grouping('alphapsili', left='alpha', right='alpha')
grouping('alphadasia', left='alpha', right='alpha')
grouping('alphapsilivaria', left='alpha', right='alpha')
grouping('alphadasiavaria', left='alpha', right='alpha')
grouping('alphapsilioxia', left='alpha', right='alpha')
grouping('alphadasiaoxia', left='alpha', right='alpha')
grouping('alphapsiliperispomeni', left='alpha', right='alpha')
grouping('alphadasiaperispomeni', left='alpha', right='alpha')
grouping('alphavaria', left='alpha', right='alpha')
grouping('alphaoxia', left='alpha', right='alpha')
grouping('alphapsiliypogegrammeni', left='alpha', right='alpha')
grouping('alphadasiaypogegrammeni', left='alpha', right='alpha')
grouping('alphapsilivariaypogegrammeni', left='alpha', right='alpha')
grouping('alphadasiavariaypogegrammeni', left='alpha', right='alpha')
grouping('alphapsilioxiaypogegrammeni', left='alpha', right='alpha')
grouping('alphadasiaoxiaypogegrammeni', left='alpha', right='alpha')
grouping('alphapsiliperispomeniypogegrammeni', left='alpha', right='alpha')
grouping('alphadasiaperispomeniypogegrammeni', left='alpha', right='alpha')
grouping('alphavrachy', left='alpha', right='alpha')
grouping('alphamacron', left='alpha', right='alpha')
grouping('alphavariaypogegrammeni', left='alpha', right='alpha')
grouping('alphaypogegrammeni', left='alpha', right='alpha')
grouping('alphaoxiaypogegrammeni', left='alpha', right='alpha')
grouping('alphaperispomeni', left='alpha', right='alpha')
grouping('alphaperispomeniypogegrammeni', left='alpha', right='alpha')
grouping('epsilonpsili', left='epsilon', right='epsilon')
grouping('epsilondasia', left='epsilon', right='epsilon')
grouping('epsilonpsilivaria', left='epsilon', right='epsilon')
grouping('epsilondasiavaria', left='epsilon', right='epsilon')
grouping('epsilonpsilioxia', left='epsilon', right='epsilon')
grouping('epsilondasiaoxia', left='epsilon', right='epsilon')
grouping('epsilonvaria', left='epsilon', right='epsilon')
grouping('epsilonoxia', left='epsilon', right='epsilon')
grouping('etapsili', left='eta', right='eta')
grouping('etadasia', left='eta', right='eta')
grouping('etapsilivaria', left='eta', right='eta')
grouping('etadasiavaria', left='eta', right='eta')
grouping('etapsilioxia', left='eta', right='eta')
grouping('etadasiaoxia', left='eta', right='eta')
grouping('etapsiliperispomeni', left='eta', right='eta')
grouping('etadasiaperispomeni', left='eta', right='eta')
grouping('etavaria', left='eta', right='eta')
grouping('etaoxia', left='eta', right='eta')
grouping('etapsiliypogegrammeni', left='eta', right='eta')
grouping('etadasiaypogegrammeni', left='eta', right='eta')
grouping('etapsilivariaypogegrammeni', left='eta', right='eta')
grouping('etadasiavariaypogegrammeni', left='eta', right='eta')
grouping('etapsilioxiaypogegrammeni', left='eta', right='eta')
grouping('etadasiaoxiaypogegrammeni', left='eta', right='eta')
grouping('etapsiliperispomeniypogegrammeni', left='eta', right='eta')
grouping('etadasiaperispomeniypogegrammeni', left='eta', right='eta')
grouping('etavariaypogegrammeni', left='eta', right='eta')
grouping('etaypogegrammeni', left='eta', right='eta')
grouping('etaoxiaypogegrammeni', left='eta', right='eta')
grouping('etaperispomeni', left='eta', right='eta')
grouping('etaperispomeniypogegrammeni', left='eta', right='eta')
grouping('iotapsili', left='iotatonos', right='iotatonos')
grouping('iotadasia', left='iotatonos', right='iotatonos')
grouping('iotavaria', left='iotatonos', right='iotatonos')
grouping('iotaoxia', left='iotatonos', right='iotatonos')
grouping('iotapsilivaria', left='iotadieresistonos', right='iotadieresistonos')
grouping('iotadasiavaria', left='iotadieresistonos', right='iotadieresistonos')
grouping('iotapsilioxia', left='iotadieresistonos', right='iotadieresistonos')
grouping('iotadasiaoxia', left='iotadieresistonos', right='iotadieresistonos')
grouping('iotapsiliperispomeni', left='iotadieresis', right='iotadieresis')
grouping('iotadasiaperispomeni', left='iotadieresis', right='iotadieresis')
grouping('iotavrachy', left='iotadieresis', right='iotadieresis')
grouping('iotamacron', left='iotadieresis', right='iotadieresis')
grouping('iotadialytikavaria', left='iotadieresis', right='iotadieresis')
grouping('iotadialytikaoxia', left='iotadieresis', right='iotadieresis')
grouping('iotaperispomeni', left='iotadieresis', right='iotadieresis')
grouping('iotadialytikaperispomeni', left='iotadieresis', right='iotadieresis')
grouping('omicronpsili', left='omicron', right='omicron')
grouping('omicrondasia', left='omicron', right='omicron')
grouping('omicronpsilivaria', left='omicron', right='omicron')
grouping('omicrondasiavaria', left='omicron', right='omicron')
grouping('omicronpsilioxia', left='omicron', right='omicron')
grouping('omicrondasiaoxia', left='omicron', right='omicron')
grouping('omicronvaria', left='omicron', right='omicron')
grouping('omicronoxia', left='omicron', right='omicron')
grouping('rhopsili', left='rho', right='omicron')
grouping('rhodasia', left='rho', right='omicron')
grouping('omegapsili', left='omicron', right='omicron')
grouping('omegadasia', left='omicron', right='omicron')
grouping('omegapsilivaria', left='omicron', right='omicron')
grouping('omegadasiavaria', left='omicron', right='omicron')
grouping('omegapsilioxia', left='omicron', right='omicron')
grouping('omegadasiaoxia', left='omicron', right='omicron')
grouping('omegapsiliperispomeni', left='omicron', right='omicron')
grouping('omegadasiaperispomeni', left='omicron', right='omicron')
grouping('omegavaria', left='omicron', right='omicron')
grouping('omegaoxia', left='omicron', right='omicron')
grouping('omegapsiliypogegrammeni', left='omicron', right='omicron')
grouping('omegadasiaypogegrammeni', left='omicron', right='omicron')
grouping('omegapsilivariaypogegrammeni', left='omicron', right='omicron')
grouping('omegadasiavariaypogegrammeni', left='omicron', right='omicron')
grouping('omegapsilioxiaypogegrammeni', left='omicron', right='omicron')
grouping('omegadasiaoxiaypogegrammeni', left='omicron', right='omicron')
grouping('omegapsiliperispomeniypogegrammeni', left='omicron', right='omicron')
grouping('omegadasiaperispomeniypogegrammeni', left='omicron', right='omicron')
grouping('omegavariaypogegrammeni', left='omicron', right='omicron')
grouping('omegaypogegrammeni', left='omicron', right='omicron')
grouping('omegaoxiaypogegrammeni', left='omicron', right='omicron')
grouping('omegaperispomeni', left='omicron', right='omicron')
grouping('omegaperispomeniypogegrammeni', left='omicron', right='omicron')
grouping('upsilonpsili', left='upsilon', right='upsilondieresistonos')
grouping('upsilondasia', left='upsilon', right='upsilondieresistonos')
grouping('upsilonvaria', left='upsilon', right='upsilondieresistonos')
grouping('upsilonoxia', left='upsilon', right='upsilondieresistonos')
grouping('upsilonpsilivaria', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilondasiavaria', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilonpsilioxia', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilondasiaoxia', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilonpsiliperispomeni', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilondasiaperispomeni', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilonvrachy', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilonmacron', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilondialytikavaria', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilondialytikaoxia', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilonperispomeni', left='upsilondieresistonos', right='upsilondieresistonos')
grouping('upsilondialytikaperispomeni', left='upsilondieresistonos', right='upsilondieresistonos')

grouping('alphadasia.sc', left='alpha.sc', right='alpha.sc')
grouping('alphadasiaoxia.sc', left='alpha.sc', right='alpha.sc')
grouping('alphadasiaoxiaypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphadasiaperispomeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphadasiaperispomeniypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphadasiavaria.sc', left='alpha.sc', right='alpha.sc')
grouping('alphadasiavariaypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphadasiaypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphamacron.sc', left='alpha.sc', right='alpha.sc')
grouping('alphaoxia.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsili.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsilioxia.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsilioxiaypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsiliperispomeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsiliperispomeniypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsilivaria.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsilivariaypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphapsiliypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('alphatonos.sc', left='alpha.sc', right='alpha.sc')
grouping('alphavaria.sc', left='alpha.sc', right='alpha.sc')
grouping('alphavrachy.sc', left='alpha.sc', right='alpha.sc')
grouping('alphaypogegrammeni.sc', left='alpha.sc', right='alpha.sc')
grouping('epsilondasia.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilondasiaoxia.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilondasiavaria.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilonoxia.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilonpsili.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilonpsilioxia.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilonpsilivaria.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilontonos.sc', left='beta.sc', right='epsilon.sc')
grouping('epsilonvaria.sc', left='beta.sc', right='epsilon.sc')
grouping('etadasia.sc', left='beta.sc', right='eta.sc')
grouping('etadasiaoxia.sc', left='beta.sc', right='eta.sc')
grouping('etadasiaoxiaypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etadasiaperispomeni.sc', left='beta.sc', right='eta.sc')
grouping('etadasiaperispomeniypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etadasiavaria.sc', left='beta.sc', right='eta.sc')
grouping('etadasiavariaypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etadasiaypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etaoxia.sc', left='beta.sc', right='eta.sc')
grouping('etapsili.sc', left='beta.sc', right='eta.sc')
grouping('etapsilioxia.sc', left='beta.sc', right='eta.sc')
grouping('etapsilioxiaypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etapsiliperispomeni.sc', left='beta.sc', right='eta.sc')
grouping('etapsiliperispomeniypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etapsilivaria.sc', left='beta.sc', right='eta.sc')
grouping('etapsilivariaypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etapsiliypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('etatonos.sc', left='beta.sc', right='eta.sc')
grouping('etavaria.sc', left='beta.sc', right='eta.sc')
grouping('etaypogegrammeni.sc', left='beta.sc', right='eta.sc')
grouping('iotadasia.sc', left='beta.sc', right='eta.sc')
grouping('iotadasiaoxia.sc', left='beta.sc', right='eta.sc')
grouping('iotadasiaperispomeni.sc', left='beta.sc', right='eta.sc')
grouping('iotadasiavaria.sc', left='beta.sc', right='eta.sc')
grouping('iotadieresis.sc', left='beta.sc', right='eta.sc')
grouping('iotamacron.sc', left='beta.sc', right='eta.sc')
grouping('iotaoxia.sc', left='beta.sc', right='eta.sc')
grouping('iotapsili.sc', left='beta.sc', right='eta.sc')
grouping('iotapsilioxia.sc', left='beta.sc', right='eta.sc')
grouping('iotapsiliperispomeni.sc', left='beta.sc', right='eta.sc')
grouping('iotapsilivaria.sc', left='beta.sc', right='eta.sc')
grouping('iotatonos.sc', left='beta.sc', right='eta.sc')
grouping('iotavaria.sc', left='beta.sc', right='eta.sc')
grouping('iotavrachy.sc', left='beta.sc', right='eta.sc')
grouping('omegadasia.sc', left='omega.sc', right='omega.sc')
grouping('omegadasiaoxia.sc', left='omega.sc', right='omega.sc')
grouping('omegadasiaoxiaypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegadasiaperispomeni.sc', left='omega.sc', right='omega.sc')
grouping('omegadasiaperispomeniypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegadasiavaria.sc', left='omega.sc', right='omega.sc')
grouping('omegadasiavariaypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegadasiaypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegaoxia.sc', left='omega.sc', right='omega.sc')
grouping('omegapsili.sc', left='omega.sc', right='omega.sc')
grouping('omegapsilioxia.sc', left='omega.sc', right='omega.sc')
grouping('omegapsilioxiaypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegapsiliperispomeni.sc', left='omega.sc', right='omega.sc')
grouping('omegapsiliperispomeniypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegapsilivaria.sc', left='omega.sc', right='omega.sc')
grouping('omegapsilivariaypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegapsiliypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omegatonos.sc', left='omega.sc', right='omega.sc')
grouping('omegavaria.sc', left='omega.sc', right='omega.sc')
grouping('omegaypogegrammeni.sc', left='omega.sc', right='omega.sc')
grouping('omicrondasia.sc', left='omicron.sc', right='omicron.sc')
grouping('omicrondasiaoxia.sc', left='omicron.sc', right='omicron.sc')
grouping('omicrondasiavaria.sc', left='omicron.sc', right='omicron.sc')
grouping('omicronoxia.sc', left='omicron.sc', right='omicron.sc')
grouping('omicronpsili.sc', left='omicron.sc', right='omicron.sc')
grouping('omicronpsilioxia.sc', left='omicron.sc', right='omicron.sc')
grouping('omicronpsilivaria.sc', left='omicron.sc', right='omicron.sc')
grouping('omicrontonos.sc', left='omicron.sc', right='omicron.sc')
grouping('omicronvaria.sc', left='omicron.sc', right='omicron.sc')
grouping('rhodasia.sc', left='beta.sc', right='rho.sc')
grouping('upsilondasia.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilondasiaoxia.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilondasiaperispomeni.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilondasiavaria.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilondieresis.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilonmacron.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilonoxia.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilontonos.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilonvaria.sc', left='upsilon.sc', right='upsilon.sc')
grouping('upsilonvrachy.sc', left='upsilon.sc', right='upsilon.sc')

grouping('anoteleia', left='periodcentered', right='periodcentered')


grouping('To-arm', left='Vo-arm', right='To-arm')
grouping('Zhe-arm', left='Zhe-arm', right='To-arm')
grouping('Gim-arm', left='Da-arm', right='Da-arm')
grouping('Ben-arm', left='Vo-arm', right='Ben-arm')
grouping('Jheh-arm', left='Za-arm', right='Za-arm')
grouping('Ech-arm', left='Seh-arm', right='Seh-arm')
grouping('Liwn-arm', left='Liwn-arm', right='Liwn-arm')
grouping('Da-arm', left='Da-arm', right='Da-arm')
grouping('Ini-arm', left='Liwn-arm', right='Ini-arm')
grouping('Et-arm', left='Vo-arm', right='Vo-arm')
grouping('Eh-arm', left='Liwn-arm', right='Eh-arm')
grouping('Za-arm', left='Za-arm', right='Za-arm')
grouping('Xeh-arm', left='Liwn-arm', right='Xeh-arm')
grouping('Ra-arm', left='Vo-arm', right='Da-arm')
grouping('Peh-arm', left='Da-arm', right='Vo-arm')
grouping('Seh-arm', left='Seh-arm', right='Seh-arm')
grouping('Yiwn-arm', left='Liwn-arm', right='Yiwn-arm')
grouping('Men-arm', left='Seh-arm')
grouping('Vew-arm', left='Ken-arm', right='Ghad-arm')
grouping('Reh-arm', left='Vo-arm', right='Reh-arm')
grouping('Vo-arm', left='Vo-arm', right='Vo-arm')
grouping('Ghad-arm', left='Da-arm', right='Ghad-arm')
grouping('Ken-arm', left='Ken-arm', right='Ken-arm')
grouping('Ayb-arm', left='Seh-arm', right='Ayb-arm')

grouping('ayb-arm', left='ayb-arm', right='ayb-arm')
grouping('ben-arm', left='ben-arm', right='ben-arm')
grouping('ca-arm', left='oh-arm', right='zhe-arm')
grouping('co-arm', left='oh-arm', right='co-arm')
grouping('da-arm', left='vo-arm', right='gim-arm')
grouping('ech-arm', left='ech-arm', right='ayb-arm')
grouping('ech_yiwn-arm', left='ech-arm', right='gim-arm')
grouping('eh-arm', left='eh-arm', right='eh-arm')
grouping('et-arm', left='ben-arm', right='vo-arm')
grouping('ghad-arm', left='vo-arm', right='za-arm')
grouping('gim-arm', left='oh-arm', right='gim-arm')
grouping('ho-arm', left='ho-arm', right='ho-arm')
grouping('ini-arm', left='ini-arm', right='vo-arm')
grouping('keh-arm', left='keh-arm', right='oh-arm')
grouping('ken-arm', left='ech-arm', right='peh-arm')
grouping('liwn-arm', left='ben-arm', right='za-arm')
grouping('men-arm', left='ayb-arm', right='men-arm')
grouping('now-arm', left='now-arm', right='ayb-arm')
grouping('oh-arm', left='oh-arm', right='oh-arm')
grouping('peh-arm', left='ayb-arm', right='peh-arm')
grouping('piwr-arm', left='ayb-arm', right='vo-arm')
grouping('ra-arm', left='vo-arm', right='ra-arm')
grouping('reh-arm', left='ben-arm', right='vo-arm')
grouping('seh-arm', left='ayb-arm', right='ayb-arm')
grouping('tiwn-arm', left='ayb-arm', right='vo-arm')
grouping('to-arm', left='ben-arm', right='to-arm')
grouping('vew-arm', left='ayb-arm', right='za-arm')
grouping('vo-arm', left='vo-arm', right='vo-arm')
grouping('xeh-arm', left='ini-arm', right='ayb-arm')
grouping('yiwn-arm', left='vo-arm', right='gim-arm')
grouping('za-arm', left='oh-arm', right='za-arm')
grouping('zhe-arm', left='oh-arm', right='zhe-arm')
grouping('ringhalfleft-arm', left='=50', right='=50')
grouping('comma-arm', left='emphasis-arm', right='emphasis-arm')
grouping('hyphen-arm', left='hyphen', right='hyphen')
grouping('apostrophe-arm', left='quoteright', right='quoteright')
grouping('za-arm.long', left='za-arm')
grouping('liwn-arm.long', left='liwn-arm')
grouping('ghad-arm.long', left='ghad-arm')
grouping('vew-arm.long', left='vew-arm')
grouping('ben-arm.short', left='ben-arm', right='ben-arm')
grouping('et-arm.short', left='et-arm', right='et-arm')
grouping('ini-arm.short', left='ini-arm', right='ini-arm')
grouping('xeh-arm.short', left='xeh-arm', right='xeh-arm')
grouping('yi-arm.short', left='yi-arm', right='yi-arm')
grouping('reh-arm.short', left='reh-arm', right='reh-arm')
grouping('co-arm.short', left='co-arm', right='co-arm')


grouping('ain-ar', left='ain-ar', right='ain-ar')
grouping('ain-ar.fina', left='ain-ar.fina', right='alefMaksura-ar.medi')
grouping('ain-ar.init', left='alefMaksura-ar.medi', right='ain-ar.init')
grouping('ain-ar.isol', left='ain-ar', right='ain-ar')
grouping('ain-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('alef-ar', left='alef-ar', right='alef-ar')
grouping('alef-ar.fina', left='alef-ar', right='alefMaksura-ar.medi')
grouping('alef-ar.isol', left='alef-ar', right='alef-ar')
grouping('alefHamzaabove-ar', left='alef-ar', right='alef-ar')
grouping('alefHamzaabove-ar.fina', left='alef-ar', right='alefMaksura-ar.medi')
grouping('alefHamzaabove-ar.isol', left='alef-ar', right='alef-ar')
grouping('alefHamzabelow-ar', left='alef-ar', right='alef-ar')
grouping('alefHamzabelow-ar.fina', left='alef-ar', right='alefMaksura-ar.medi')
grouping('alefHamzabelow-ar.isol', left='alef-ar', right='alef-ar')
grouping('alefMadda-ar', left='alef-ar', right='alef-ar')
grouping('alefMadda-ar.fina', left='alef-ar', right='alefMaksura-ar.medi')
grouping('alefMadda-ar.isol', left='alef-ar', right='alef-ar')
grouping('alefMaksura-ar', left='seen-ar', right='alefMaksura-ar')
grouping('alefMaksura-ar.fina', left='alefMaksura-ar.fina', right='alefMaksura-ar.medi')
grouping('alefMaksura-ar.fina.calt', left='alefMaksura-ar.fina', right='alefMaksura-ar.medi')
grouping('alefMaksura-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('alefMaksura-ar.isol', left='seen-ar', right='alefMaksura-ar')
# grouping('alefMaksura-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('alefWasla-ar', left='alef-ar', right='alef-ar')
grouping('alefWasla-ar.fina', left='alef-ar', right='alefMaksura-ar.medi')
grouping('alefWasla-ar.isol', left='alef-ar', right='alef-ar')
grouping('beeh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('beeh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('beeh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('beeh-ar.init.calt', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('beeh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('beeh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('beh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('beh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('beh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('beh-ar.init.calt', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('beh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('beh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('beheh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('beheh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('beheh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('beheh-ar.init.calt', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('beheh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('beheh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('dad-ar', left='seen-ar', right='sad-ar')
grouping('dad-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('dad-ar.init', left='alefMaksura-ar.medi', right='sad-ar')
grouping('dad-ar.isol', left='seen-ar', right='sad-ar')
grouping('dad-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('dahal-ar', left='thal-ar', right='dal-ar')
grouping('dahal-ar.fina', left='thal-ar', right='alefMaksura-ar.medi')
grouping('dahal-ar.isol', left='thal-ar', right='dal-ar')
grouping('dal-ar', left='dal-ar', right='dal-ar')
grouping('dal-ar.fina', left='dal-ar', right='alefMaksura-ar.medi')
grouping('dal-ar.isol', left='dal-ar', right='dal-ar')
grouping('ddahal-ar', left='dal-ar', right='dal-ar')
grouping('ddahal-ar.fina', left='dal-ar', right='alefMaksura-ar.medi')
grouping('ddahal-ar.isol', left='dal-ar', right='dal-ar')
grouping('ddal-ar', left='thal-ar', right='dal-ar')
grouping('ddal-ar.fina', left='thal-ar', right='alefMaksura-ar.medi')
grouping('ddal-ar.isol', left='thal-ar', right='dal-ar')
grouping('behDotless-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('behDotless-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('behDotless-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('fehDotless-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('fehDotless-ar.init', left='alefMaksura-ar.medi')
grouping('fehDotless-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('qafDotless-ar', left='seen-ar')
grouping('qafDotless-ar.fina', left='qafDotless-ar', right='alefMaksura-ar.medi')
grouping('dul-ar', left='thal-ar', right='dal-ar')
grouping('dul-ar.fina', left='thal-ar', right='alefMaksura-ar.medi')
grouping('dul-ar.isol', left='thal-ar', right='dal-ar')
grouping('dyeh-ar', left='hah-ar', right='hah-ar')
grouping('dyeh-ar.fina', left='hah-ar', right='alefMaksura-ar.medi')
grouping('dyeh-ar.init', left='alefMaksura-ar.medi', right='jeem-ar.init')
grouping('dyeh-ar.isol', left='hah-ar', right='hah-ar')
grouping('dyeh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('e-ar.fina', left='alefMaksura-ar.fina', right='alefMaksura-ar.medi')
grouping('e-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('e-ar.isol', left='seen-ar', right='alefMaksura-ar')
grouping('e-ar.isol2', left='seen-ar', right='alefMaksura-ar')
grouping('e-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('feh-ar', left='dotlessbeh-ar', right='fehDotless-ar.isol')
grouping('feh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('feh-ar.init', left='alefMaksura-ar.medi', right='fehDotless-ar.isol')
grouping('feh-ar.isol', left='dotlessbeh-ar', right='fehDotless-ar.isol')
grouping('feh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('gaf-ar', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('gaf-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('gaf-ar.init', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('gaf-ar.isol', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('gaf-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('ghain-ar', left='ain-ar', right='ain-ar')
grouping('ghain-ar.fina', left='ain-ar.fina', right='alefMaksura-ar.medi')
grouping('ghain-ar.init', left='alefMaksura-ar.medi', right='ain-ar.init')
grouping('ghain-ar.isol', left='ain-ar', right='ain-ar')
grouping('ghain-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('gueh-ar', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('gueh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('gueh-ar.init', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('gueh-ar.isol', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('gueh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('hah-ar', left='hah-ar', right='hah-ar')
grouping('hah-ar.fina', left='hah-ar', right='alefMaksura-ar.medi')
grouping('hah-ar.init', left='alefMaksura-ar.medi', right='jeem-ar.init')
grouping('hah-ar.isol', left='hah-ar', right='hah-ar')
grouping('hah-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('heh-ar', left='heh-ar', right='heh-ar')
grouping('heh-ar.fina', left='heh-ar.fina', right='alefMaksura-ar.medi')
grouping('heh-ar.init', left='alefMaksura-ar.medi', right='heh-ar.init')
grouping('heh-ar.isol', left='heh-ar', right='heh-ar')
grouping('heh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('hehDoachashmee-ar', left='hehDoachashmee-ar', right='heh-ar.init')
grouping('hehDoachashmee-ar.fina', left='hehDoachashmee-ar', right='alefMaksura-ar.medi')
grouping('hehDoachashmee-ar.init', left='alefMaksura-ar.medi', right='heh-ar.init')
grouping('hehDoachashmee-ar.isol', left='hehDoachashmee-ar', right='heh-ar.init')
grouping('hehDoachashmee-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('hehgoal-ar', left='heh-ar', right='heh-ar')
grouping('hehgoal-ar.fina', left=None, right='alefMaksura-ar.medi')
grouping('hehgoal-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('hehgoal-ar.init.calt', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('hehgoal-ar.isol', left='heh-ar', right='heh-ar')
grouping('hehgoal-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('hehHamzaabove-ar', left='heh-ar', right='heh-ar')
grouping('hehHamzaabove-ar.fina', left='heh-ar.fina', right='alefMaksura-ar.medi')
grouping('hehHamzaabove-ar.isol', left='heh-ar', right='heh-ar')
grouping('jeem-ar', left='hah-ar', right='hah-ar')
grouping('jeem-ar.fina', left='hah-ar', right='alefMaksura-ar.medi')
grouping('jeem-ar.init', left='alefMaksura-ar.medi', right='jeem-ar.init')
grouping('jeem-ar.isol', left='hah-ar', right='hah-ar')
grouping('jeem-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('jeh-ar', left='zain-ar', right='reh-ar')
grouping('jeh-ar.fina', left='zain-ar', right='alefMaksura-ar.medi')
grouping('jeh-ar.isol', left='zain-ar', right='reh-ar')
grouping('kaf-ar', left='dotlessbeh-ar', right='kaf-ar')
grouping('kaf-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('kaf-ar.init', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('kaf-ar.init.calt', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('kaf-ar.isol', left='dotlessbeh-ar', right='kaf-ar')
grouping('kaf-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('kaf-ar.medi.calt', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('kashida-ar', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('keheh-ar', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('keheh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('keheh-ar.init', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('keheh-ar.init.calt', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('keheh-ar.isol', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('keheh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('keheh-ar.medi.calt', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('khah-ar', left='hah-ar', right='hah-ar')
grouping('khah-ar.fina', left='hah-ar', right='alefMaksura-ar.medi')
grouping('khah-ar.init', left='alefMaksura-ar.medi', right='jeem-ar.init')
grouping('khah-ar.isol', left='hah-ar', right='hah-ar')
grouping('khah-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('kirghizoe-ar', left='waw-ar', right='waw-ar')
grouping('kirghizoe-ar.fina', left='waw-ar', right='alefMaksura-ar.medi')
grouping('kirghizoe-ar.isol', left='wawHamzaabove-ar', right='waw-ar')
grouping('kirghizyu-ar', left='wawHamzaabove-ar', right='waw-ar')
grouping('kirghizyu-ar.fina', left='wawHamzaabove-ar', right='alefMaksura-ar.medi')
grouping('kirghizyu-ar.isol', left='wawHamzaabove-ar', right='waw-ar')
grouping('lam-ar', left='seen-ar', right='lam-ar')
grouping('lam-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('lam-ar.init', left='alefMaksura-ar.medi', right='kaf-ar')
grouping('lam-ar.isol', left='seen-ar', right='lam-ar')
grouping('lam-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('lam_alef-ar', left='lam_alef-ar', right='lam_alef-ar')
grouping('lam_alef-ar.fina', left='lam_alef-ar.fina', right='alefMaksura-ar.medi')
grouping('lam_alefHamzaabove-ar', left='lam_alef-ar', right='lam_alef-ar')
grouping('lam_alefHamzaabove-ar.fina', left='lam_alef-ar.fina', right='alefMaksura-ar.medi')
grouping('lam_alefHamzabelow-ar', left='lam_alef-ar', right='lam_alef-ar')
grouping('lam_alefHamzabelow-ar.fina', left='lam_alef-ar.fina', right='alefMaksura-ar.medi')
grouping('lam_alefMadda-ar', left='lam_alef-ar', right='lam_alef-ar')
grouping('lam_alefMadda-ar.fina', left='lam_alef-ar.fina', right='alefMaksura-ar.medi')
grouping('meem-ar', left='meem-ar', right='meem-ar')
grouping('meem-ar.fina', left='meem-ar.fina', right='alefMaksura-ar.medi')
grouping('meem-ar.init', left='alefMaksura-ar.medi', right=None)
grouping('meem-ar.isol', left='meem-ar', right='meem-ar')
grouping('meem-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('ng-ar', left='dotlessbeh-ar', right='kaf-ar')
grouping('ng-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('ng-ar.init', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('ng-ar.isol', left='dotlessbeh-ar', right='kaf-ar')
grouping('ng-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('ngoeh-ar', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('ngoeh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('ngoeh-ar.init', left='alefMaksura-ar.medi', right='kaf-ar.init')
grouping('ngoeh-ar.isol', left='dotlessbeh-ar', right='kaf-ar.init')
grouping('ngoeh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('noon-ar', left='seen-ar', right='noonghunna-ar')
grouping('noon-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('noon-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('noon-ar.isol', left='seen-ar', right='noonghunna-ar')
grouping('noon-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('noonghunna-ar', left='seen-ar', right='noonghunna-ar')
grouping('noonghunna-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('noonghunna-ar.isol', left='seen-ar', right='noonghunna-ar')
grouping('nyeh-ar', left='hah-ar', right='hah-ar')
grouping('nyeh-ar.fina', left='hah-ar', right='alefMaksura-ar.medi')
grouping('nyeh-ar.init', left='alefMaksura-ar.medi', right='jeem-ar.init')
grouping('nyeh-ar.isol', left='hah-ar', right='hah-ar')
grouping('nyeh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('oe-ar.fina', left='wawHamzaabove-ar', right='alefMaksura-ar.medi')
grouping('oe-ar.isol', left='wawHamzaabove-ar', right='waw-ar')
grouping('oe-ar.isol2', left='wawHamzaabove-ar', right='waw-ar')
grouping('peh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('peh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('peh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('peh-ar.init.calt', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('peh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('peh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('peheh-ar', left='dotlessbeh-ar', right='fehDotless-ar.isol')
grouping('peheh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('peheh-ar.init', left='alefMaksura-ar.medi', right='fehDotless-ar.isol')
grouping('peheh-ar.isol', left='dotlessbeh-ar', right='fehDotless-ar.isol')
grouping('peheh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('qaf-ar', left='seen-ar', right='dotlessqaf-ar')
grouping('qaf-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('qaf-ar.init', left='alefMaksura-ar.medi', right='fehDotless-ar.isol')
grouping('qaf-ar.isol', left='seen-ar', right='dotlessqaf-ar')
grouping('qaf-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('reh-ar', left='reh-ar', right='reh-ar')
grouping('reh-ar.fina', left='reh-ar', right='alefMaksura-ar.medi')
grouping('reh-ar.isol', left='reh-ar', right='reh-ar')
grouping('rnoon-ar', left='seen-ar', right='noon-ar')
grouping('rnoon-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('rnoon-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('rnoon-ar.isol', left='seen-ar', right='noon-ar')
grouping('rnoon-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('rreh-ar', left='zain-ar', right='reh-ar')
grouping('rreh-ar.fina', left='zain-ar', right='alefMaksura-ar.medi')
grouping('rreh-ar.isol', left='zain-ar', right='reh-ar')
grouping('sad-ar', left='seen-ar', right='sad-ar')
grouping('sad-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('sad-ar.init', left='alefMaksura-ar.medi', right='sad-ar')
grouping('sad-ar.isol', left='seen-ar', right='sad-ar')
grouping('sad-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('seen-ar', left='seen-ar', right='dotlessbeh-ar')
grouping('seen-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('seen-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('seen-ar.isol', left='seen-ar', right='dotlessbeh-ar')
grouping('seen-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('sheen-ar', left='seen-ar', right='dotlessbeh-ar')
grouping('sheen-ar.fina', left='seen-ar', right='alefMaksura-ar.medi')
grouping('sheen-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('sheen-ar.isol', left='seen-ar', right='dotlessbeh-ar')
grouping('sheen-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('tah-ar', left='tah-ar', right='sad-ar')
grouping('tah-ar.fina', left='tah-ar', right='alefMaksura-ar.medi')
grouping('tah-ar.init', left='alefMaksura-ar.medi', right='sad-ar')
grouping('tah-ar.isol', left='tah-ar', right='sad-ar')
grouping('tah-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('tcheh-ar', left='hah-ar', right='hah-ar')
grouping('tcheh-ar.fina', left='hah-ar', right='alefMaksura-ar.medi')
grouping('tcheh-ar.init', left='alefMaksura-ar.medi', right='jeem-ar.init')
grouping('tcheh-ar.isol', left='hah-ar', right='hah-ar')
grouping('tcheh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('tcheheh-ar', left='hah-ar', right='hah-ar')
grouping('tcheheh-ar.fina', left='hah-ar', right='alefMaksura-ar.medi')
grouping('tcheheh-ar.init', left='alefMaksura-ar.medi', right='jeem-ar.init')
grouping('tcheheh-ar.isol', left='hah-ar', right='hah-ar')
grouping('tcheheh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('teh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('teh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('teh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('teh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('teh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('teheh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('teheh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('teheh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('teheh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('teheh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('tehMarbuta-ar', left='heh-ar', right='heh-ar')
grouping('tehMarbuta-ar.fina', left='heh-ar.fina', right='alefMaksura-ar.medi')
grouping('tehMarbuta-ar.isol', left='heh-ar', right='heh-ar')
grouping('thal-ar', left='thal-ar', right='dal-ar')
grouping('thal-ar.fina', left='thal-ar', right='alefMaksura-ar.medi')
grouping('thal-ar.isol', left='thal-ar', right='dal-ar')
grouping('theh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('theh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('theh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('theh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('theh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('tteh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('tteh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('tteh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('tteh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('tteh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('tteheh-ar', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('tteheh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('tteheh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('tteheh-ar.isol', left='dotlessbeh-ar', right='dotlessbeh-ar')
grouping('tteheh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('u-ar.fina', left='wawHamzaabove-ar', right='alefMaksura-ar.medi')
grouping('u-ar.isol', left='wawHamzaabove-ar', right='waw-ar')
grouping('u-ar.isol2', left='wawHamzaabove-ar', right='waw-ar')
grouping('uHamzaabove-ar', left='wawHamzaabove-ar', right='waw-ar')
grouping('ve-ar', left='wawHamzaabove-ar', right='waw-ar')
grouping('ve-ar.fina', left='wawHamzaabove-ar', right='alefMaksura-ar.medi')
grouping('ve-ar.isol', left='wawHamzaabove-ar', right='waw-ar')
grouping('veh-ar', left='dotlessbeh-ar', right='fehDotless-ar.isol')
grouping('veh-ar.fina', left='dotlessbeh-ar', right='alefMaksura-ar.medi')
grouping('veh-ar.init', left='alefMaksura-ar.medi', right='fehDotless-ar.isol')
grouping('veh-ar.isol', left='dotlessbeh-ar', right='fehDotless-ar.isol')
grouping('veh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('waw-ar', left='waw-ar', right='waw-ar')
grouping('waw-ar.fina', left='waw-ar', right='alefMaksura-ar.medi')
grouping('waw-ar.isol', left='waw-ar', right='waw-ar')
grouping('wawHamzaabove-ar', left='wawHamzaabove-ar', right='waw-ar')
grouping('wawHamzaabove-ar.fina', left='wawHamzaabove-ar', right='alefMaksura-ar.medi')
grouping('wawHamzaabove-ar.isol', left='wawHamzaabove-ar', right='waw-ar')
grouping('yeh-ar', left='seen-ar', right='alefMaksura-ar')
grouping('yeh-ar.fina', left='alefMaksura-ar.fina', right='alefMaksura-ar.medi')
grouping('yeh-ar.fina.calt', left='alefMaksura-ar.fina', right='alefMaksura-ar.medi')
grouping('yeh-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('yeh-ar.init.calt', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('yeh-ar.isol', left='seen-ar', right='alefMaksura-ar')
grouping('yeh-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('yehbarree-ar', left='yehbarree-ar', right='yehbarree-ar')
grouping('yehbarree-ar.fina', left='yehbarree-ar.fina', right='alefMaksura-ar.medi')
grouping('yehbarree-ar.isol', left='yehbarree-ar', right='yehbarree-ar')
grouping('yehbarreeHamzaabove-ar', left='yehbarreeHamzaabove-ar', right='yehbarree-ar')
grouping('yehbarreeHamzaabove-ar.fina', left='yehbarree-ar.fina', right='alefMaksura-ar.medi')
grouping('yehbarreeHamzaabove-ar.isol', left='yehbarreeHamzaabove-ar', right='yehbarree-ar')
grouping('yehHamzaabove-ar', left='seen-ar', right='alefMaksura-ar')
grouping('yehHamzaabove-ar.fina', left='alefMaksura-ar.fina', right='alefMaksura-ar.medi')
grouping('yehHamzaabove-ar.fina.calt', left='alefMaksura-ar.fina', right='alefMaksura-ar.medi')
grouping('yehHamzaabove-ar.init', left='alefMaksura-ar.medi', right='dotlessbeh-ar')
grouping('yehHamzaabove-ar.isol', left='seen-ar', right='alefMaksura-ar')
grouping('yehHamzaabove-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('yu-ar', left='wawHamzaabove-ar', right='waw-ar')
grouping('yu-ar.fina', left='wawHamzaabove-ar', right='alefMaksura-ar.medi')
grouping('yu-ar.isol', left='wawHamzaabove-ar', right='waw-ar')
grouping('zah-ar', left='tah-ar', right='sad-ar')
grouping('zah-ar.fina', left='tah-ar', right='alefMaksura-ar.medi')
grouping('zah-ar.init', left='alefMaksura-ar.medi', right='sad-ar')
grouping('zah-ar.isol', left='tah-ar', right='sad-ar')
grouping('zah-ar.medi', left='alefMaksura-ar.medi', right='alefMaksura-ar.medi')
grouping('zain-ar', left='zain-ar', right='reh-ar')
grouping('zain-ar.fina', left='zain-ar', right='alefMaksura-ar.medi')
grouping('zain-ar.isol', left='zain-ar', right='reh-ar')
grouping('zero-ar', left='zero-ar', right='zero-ar')
grouping('one-ar', left='one-ar', right='one-ar')
grouping('two-ar', left='one-ar', right='two-ar')
grouping('three-ar', left='one-ar', right='two-ar')
grouping('four-ar', left='four-ar', right='four-ar')
grouping('four-ar.urdu', left='four-ar.urdu', right='four-ar.urdu')
grouping('five-ar', left='five-ar', right='five-ar')
grouping('six-ar', left='six-ar', right='six-ar')
grouping('seven-ar', left='one-ar', right='seven-ar')
grouping('eight-ar', left='eight-ar', right='eight-ar')
grouping('nine-ar', left='nine-ar', right='nine-ar')
grouping('zero-persian', left='zero-ar', right='zero-ar')
grouping('one-persian', left='one-ar', right='one-persian')
grouping('two-persian', left='one-ar', right='two-ar')
grouping('three-persian', left='one-ar', right='two-ar')
grouping('four-persian', left='one-ar', right='four-persian')
grouping('five-persian', left='five-persian', right='five-persian')
grouping('six-persian', left='six-persian', right='six-persian')
grouping('seven-persian', left='seven-persian', right='seven-persian')
grouping('eight-persian', left='eight-ar', right='eight-ar')
grouping('nine-persian', left='nine-ar', right='nine-ar')


grouping('jha-deva.loclNEP', left='bha-deva', right='ka-deva')
grouping('jh-deva.loclNEP', left='bha-deva', right='k-deva')

grouping('_part.bar', left='=50', right='=50')


for g in [x.parent for x in Glyphs.font.selectedLayers]:
    gM = grouping.glyphs.get(g.name, None)

    if gM is not None:
        if gM.left == g.name:
            gM.left = None
        if gM.right == g.name:
            gM.right = None
        if gM.width == g.name:
            gM.width = None

        g.leftMetricsKey = None
        g.rightMetricsKey = None
        g.widthMetricsKey = None

        if gM.left is not None:
            if isinstance(gM.left, int):
                for l in g.layers:
                    l.LSB = gM.left
            else:
                g.leftMetricsKey = gM.left

        if gM.width is not None:
            if isinstance(gM.width, int):
                for l in g.layers:
                    l.width = gM.width
            else:
                g.widthMetricsKey = gM.width

        if gM.right is not None and (gM.width is None or gM.left is None):
            if isinstance(gM.right, int):
                for l in g.layers:
                    l.RSB = gM.right
            else:
                g.rightMetricsKey = gM.right

    elif '_' in g.name:
        baseName1, x, styleSuffix = g.name.partition('.')

        if styleSuffix and styleSuffix not in ['liga', 'dlig', 'rlig']:
            styleSuffix = '.' + styleSuffix
        else:
            styleSuffix = ''

        baseName, x, suffix = baseName1.partition('-')
        if suffix:
            suffix = '-' + suffix

        nameParts = baseName.split('_')
        leftGN = nameParts[0] + suffix + styleSuffix
        rightGN = nameParts[-1] + suffix + styleSuffix

        if Glyphs.font.glyphs[leftGN]:
            g.leftMetricsKey = leftGN
        if Glyphs.font.glyphs[rightGN]:
            g.rightMetricsKey = rightGN

    elif g.category == 'Mark':
        g.leftMetricsKey = '=50'
        g.rightMetricsKey = '=50'

    for l in g.layers:
        l.syncMetrics()
